In [292]:
import pandas as pd
import numpy as np

In [293]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [294]:
data1 = pd.read_csv('/independent-house - independent-house.csv')

In [295]:
data1.sample(2)

,property_name,link,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
384,3 Bedroom House for sale in New Palam Vihar,https://www.99acres.com/3-bhk-bedroom-independ...,NaN,1 Crore,"₹ 8,796/sq.ft.",(100 sq.m.) Plot Area,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,3 Bedrooms,2 Bathrooms,2 Balconies,Pooja Room,"Q-148, New Palam Vihar, Phase-2, Near Royal Oa...",1 Floors,North,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Ground and first floor, Ground floor: Ground f...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5...",K38173331
1017,6 Bedroom House for sale in Uppals Southend,https://www.99acres.com/6-bhk-bedroom-independ...,Uppal Southend4.0 ★,3.75 Crore,"₹ 25,562/sq.ft.",(136 sq.m.) Built-up Area,Built Up area: 163 (136.29 sq.m.),6 Bedrooms,6 Bathrooms,3+ Balconies,Study Room,"Uppals Southend, Gurgaon, Haryana",3 Floors,East,5 to 10 Year Old,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...",Uppal southend sector 49.Gated society. Near b...,"['12 Fan', '1 Exhaust Fan', '6 Geyser', '24 Li...","['Feng Shui / Vaastu Compliant', 'Maintenance ...","['Environment5 out of 5', 'Safety5 out of 5', ...",H64867042

In [296]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    1095 non-null   object
 1   link             1095 non-null   object
 2   society          471 non-null    object
 3   price            968 non-null    object
 4   rate             1054 non-null   object
 5   area             1095 non-null   object
 6   areaWithType     987 non-null    object
 7   bedRoom          987 non-null    object
 8   bathroom         987 non-null    object
 9   balcony          987 non-null    object
 10  additionalRoom   589 non-null    object
 11  address          1031 non-null   object
 12  noOfFloor        967 non-null    object
 13  facing           674 non-null    object
 14  agePossession    987 non-null    object
 15  nearbyLocations  913 non-null    object
 16  description      1036 non-null   object
 17  furnishDetails   743 non-null    object
 18  features         674 non-null    object
 19  rating           907 non-null    object
 20  property_id      1036 non-null   object
dtypes: object(21)
memory usage: 179.8+ KB

In [297]:
data.isnull().sum()

property_name        0
link                 0
society            624
price              127
rate                41
area                 0
areaWithType       108
bedRoom            108
bathroom           108
balcony            108
additionalRoom     506
address             64
noOfFloor          128
facing             421
agePossession      108
nearbyLocations    182
description         59
furnishDetails     352
features           421
rating             188
property_id         59
dtype: int64

In [298]:
data1.duplicated().sum()

13

In [299]:
data1.columns

Index(['property_name', 'link', 'society', 'price', 'rate', 'area',
       'areaWithType', 'bedRoom', 'bathroom', 'balcony', 'additionalRoom',
       'address', 'noOfFloor', 'facing', 'agePossession', 'nearbyLocations',
       'description', 'furnishDetails', 'features', 'rating', 'property_id'],
      dtype='object')

In [300]:
data1.drop(columns=['link','property_id'],inplace=True)

In [301]:
data1.columns

Index(['property_name', 'society', 'price', 'rate', 'area', 'areaWithType',
       'bedRoom', 'bathroom', 'balcony', 'additionalRoom', 'address',
       'noOfFloor', 'facing', 'agePossession', 'nearbyLocations',
       'description', 'furnishDetails', 'features', 'rating'],
      dtype='object')

In [302]:
l = []
for i in data1.columns:
  l.append(i.upper())

In [303]:
data1.columns = l

In [304]:
data1.sample(2)

,PROPERTY_NAME,SOCIETY,PRICE,RATE,AREA,AREAWITHTYPE,BEDROOM,BATHROOM,BALCONY,ADDITIONALROOM,ADDRESS,NOOFFLOOR,FACING,AGEPOSSESSION,NEARBYLOCATIONS,DESCRIPTION,FURNISHDETAILS,FEATURES,RATING
373,4 Bedroom House for sale in Sector 52 Gurgaon,NaN,NaN,NaN,(201 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
251,8 Bedroom House for sale in Sector 56 Gurgaon,NaN,7.25 Crore,"₹ 29,336/sq.ft.",(253 sq.m.) Plot Area,Plot area 303(253.35 sq.m.),8 Bedrooms,8 Bathrooms,3+ Balconies,NaN,"Sector 56 Gurgaon, Gurgaon, Haryana",0 Floors,North-East,5 to 10 Year Old,"['Sector metro station', 'Sector metro station...","The property is located in sector 56, next to ...","['15 Fan', '15 Light', '1 Modular Kitchen', 'N...","['High Ceiling Height', 'Natural Light', 'Airy...","['Environment4 out of 5', 'Lifestyle5 out of 5..."

In [305]:
data1['SOCIETY'].value_counts()

SOCIETY
Vipul Tatvam Villa                                   27
International City by SOBHA Phase 2                  26
Emaar MGF Marbella                                   26
International City by Sobha Phase 1                  23
Unitech Uniworld Resorts                             14
DLF City Plots                                       11
DLF City Plots Phase 2                               11
Unitech Espace                                       11
Bptp Visionnaire                                      9
Eldeco Mansionz                                       9
Uppal Southend4.0 ★                                   9
Not Applicable                                        7
Experion Windchants3.8 ★                              6
Ansals Palam Vihar                                    6
Sushant Lok 1 Builder Floors                          6
DLF New Town Heights 24.0 ★                           5
DLF City Phase 1                                      5
Vatika India Next4.1 ★                                4
Unitech Nirvana Birch Court                           4
Ansal Sushant Lok Plots4.1 ★                          4
nul                                                   4
Ansals Florence Villa                                 4
Unitech Aspen Greens                                  4
DLF Alameda                                           4
Vatika Signature Villas                               3
Eros Rosewood City4.0 ★                               3
Sector 14 RWA                                         3
Eros Rosewood Villas                                  3
Palam Vihar Extension West Zone RWA                   3
Malibu Towne                                          3
Housing Board Colony                                  3
BPTP Astaire Gardens3.7 ★                             3
Rattan Garden                                         3
Hans Enclave                                          3
HUDA Ashok Vihar Phase 13.9 ★                         3
Bestech Park View Ananda4.2 ★                         3
SS Aaron Ville                                        3
Silverglades Tarudhan Valley Golf Resort              3
Tata Primanti4.1 ★                                    3
Puri Diplomatic Greens4.0 ★                           3
Luxury DLF City Floors                                3
Central Park Flower Valley                            3
DLF City Plots Phase 3                                3
Anant Raj Estates                                     3
Suncity Township4.1 ★                                 2
IFFCO Nagar and 17B RWA                               2
Bhim Garh Kheri                                       2
Sobha City                                            2
DLF South City 1                                      2
Ansal Sushant Residency                               2
Ardee City3.8 ★                                       2
DLF New Town Heights3.7 ★                             2
Signature Global City 92                              2
Satya The Hermitage3.5 ★                              2
Unitech Deerwood Chase                                2
Suncity Essel Towers4.2 ★                             2
Emaar The Palm Springs                                2
Project Mianwali Colony                               2
Nirvana Cedar Crest                                   2
Ansal API Esencia3.7 ★                                2
SS Hibiscus                                           2
Saksham Welfare Association                           2
Unitech Palms South City 1                            2
BPTP Pedestal                                         2
RWA Sector 46                                         2
Sector 38 RWA                                         2
Project Housing Board Colony                          2
Unitech Escape3.8 ★                                   2
DLF City Plots Phase 4                                2
Emaar Emerald Hills4.1 ★                              2
shivpuri                                              2
Spaze Privy3.9 ★                                      2
Om Nagar, Sector-11                                   1
Ireo Victory Valley4.1 ★                              1
Grover Homes Sec 4                                    1
4S Aradhya Homes                                      1
Ansal API Spanish Court                               1
secter 16a daultabad faridabad house no 313           1
Central Park Flower Valley Cerise Floors              1
FLOOR WISE DESIGNER KOTHI                             1
Birla Navya                                           1
Kothi                                                 1
rajendra park sec 105                                 1
nirvana country                                       1
Smart World Orchard                                   1
Landmark House                                        1
cloudnine cottages                                    1
u block dlf phase 3 road no 21                        1
Sector 15 Part 2 RWA                                  1
Nitin Vihar                                           1
Ansal                                                 1
Ashok vihar phase III Extension                       1
Ansal Heights3.2 ★                                    1
rattan vihar rajendra park                            1
Signature Global City 63A                             1
DLF City Plot Phase 3                                 1
Adani Brahma Samsara4.2 ★                             1
Ansal Florence Super                                  1
Unitech South City 23.8 ★                             1
Sheetla Enclave                                       1
patel nager house no 927/5                            1
Huda Floor                                            1
Huda                                                  1
Anant Raj Manor Villas                                1
Sector 57 Huda                                        1
Godrej Meridien                                       1
Ansal Sushant Lok 2                                   1
The Laburnum                                          1
Vatika Independent Floors3.8 ★                        1
Arjun Marg/ Sector- 26 Phase- 1/ Golf Course Road     1
Sector-17C                                            1
DLF Pink Town House4.0 ★                              1
huda sector-56 gurgaon                                1
Satya The Legend3.8 ★                                 1
Prem Kunj                                             1
Ireo Victory Valley4.0 ★                              1
Independent House Sector 45                           1
Ashok Vihar Phase 3 Gurgaon                           1
Farrukhnagar                                          1
Unitech Greenwood City3.6 ★                           1
Vatika The Seven Lamps3.8 ★                           1
Nirvana Country                                       1
Ansal Sushant Lok                                     1
Central Park                                          1
Signature Global City 81                              1
Signature Global City                                 1
DLF Floors Phase 3                                    1
sneh vihar                                            1
Suncity Avenue 76                                     1
DLF The Arbour                                        1
Surendra Homes Dayanand Colony                        1
Laxmi Garden Sector-11                                1
DLF Gardencity Enclave                                1
Tulip Yellow                                          1
shree krishna homes                                   1
Smart World Gems                                      1
Ganpati Heights Apartment                             1
Hero Homes                                            1
Jacobpura Gurugram                                    1
Anand Garden, Sector-105                              1
Rajendra Park Gurgaon                                 1
RK Excelo                                             1
DLF The Grove                                         1
house number B-34                                     1
Shri Shyam Residency                                  1
ATS Tourmaline3.9 ★                                   1
Bhawani enclave                                       1
Vatika Sovereign Next                                 1
MANOHAR NAGAR                                         1
Laxman vihar phase 2                                  1
Anamika Enclave                                       1
bhim nagar, sector 6                                  1
Emaar MGF The Palm Drive4.1 ★                         1
All Punjabi Welfare Association                       1
Tulip Ivory3.5 ★                                      1
Huda Plots                                            1
DLF Garden City Floors                                1
Ansal Celebrity Homes                                 1
mian wali                                             1
SS Omnia                                              1
Bhim Nagar Society                                    1
Anshul                                                1
Sare Crescent Parc Royal Greens Phase 1               1
Ninex City                                            1
Vipul World3.9 ★                                      1
Greenopolis                                           1
Ansal Esencia Sovereign Floors                        1
Nirmal Enclave, Maruti Kunj Road                      1
jacob pura                                            1
mahavir pura                                          1
Raj Villas                                            1
sector 37                                             1
Shivaji Nagar Residential                             1
private house                                         1
Surat nagar phase 2                                   1
DLF City Plot Phase 4                                 1
Sai Kripa Floors 5                                    1
Naman Residency                                       1
Krishna Palace                                        1
Signature Global Park4.0 ★                            1
Huda Flats                                            1
Jacobpura                                             1
Indiabulls Centrum Park3.7 ★                          1
Madan puri                                            1
My Home                                               1
ROW HOUSE                                             1
HUDA Plot Sector 38                                   1
HUDA Housing Board Colony4.1 ★                        1
Name: count, dtype: int64

In [306]:
data1['SOCIETY'] = data1['SOCIETY'].astype('str')

In [307]:
data1.shape

(1095, 19)

In [308]:
import re
data1['SOCIETY'] = data1['SOCIETY'].apply(lambda x: re.sub(r'\d+(\.\d+)?\s?★',"",str(x)).strip()).str.lower()

In [309]:
data1['SOCIETY'].value_counts()

SOCIETY
nan                                                  624
vipul tatvam villa                                    27
international city by sobha phase 2                   26
emaar mgf marbella                                    26
international city by sobha phase 1                   23
unitech uniworld resorts                              14
dlf city plots phase 2                                11
unitech espace                                        11
dlf city plots                                        11
bptp visionnaire                                       9
uppal southend                                         9
eldeco mansionz                                        9
dlf new town heights                                   7
not applicable                                         7
experion windchants                                    6
sushant lok 1 builder floors                           6
ansals palam vihar                                     6
dlf city phase 1                                       5
dlf alameda                                            4
unitech nirvana birch court                            4
unitech aspen greens                                   4
ansals florence villa                                  4
nul                                                    4
vatika india next                                      4
ansal sushant lok plots                                4
eros rosewood villas                                   3
bptp astaire gardens                                   3
bestech park view ananda                               3
huda ashok vihar phase                                 3
hans enclave                                           3
housing board colony                                   3
eros rosewood city                                     3
palam vihar extension west zone rwa                    3
malibu towne                                           3
sector 14 rwa                                          3
vatika signature villas                                3
ss aaron ville                                         3
rattan garden                                          3
silverglades tarudhan valley golf resort               3
tata primanti                                          3
luxury dlf city floors                                 3
puri diplomatic greens                                 3
dlf city plots phase 3                                 3
central park flower valley                             3
anant raj estates                                      3
suncity essel towers                                   2
iffco nagar and 17b rwa                                2
bhim garh kheri                                        2
sobha city                                             2
dlf south city 1                                       2
ardee city                                             2
ansal sushant residency                                2
unitech escape                                         2
satya the hermitage                                    2
suncity township                                       2
unitech deerwood chase                                 2
nirvana country                                        2
emaar the palm springs                                 2
project housing board colony                           2
ansal api esencia                                      2
ireo victory valley                                    2
ss hibiscus                                            2
saksham welfare association                            2
unitech palms south city 1                             2
bptp pedestal                                          2
rwa sector 46                                          2
sector 38 rwa                                          2
nirvana cedar crest                                    2
signature global city 92                               2
dlf city plots phase 4                                 2
project mianwali colony                                2
emaar emerald hills                                    2
spaze privy                                            2
shivpuri                                               2
ninex city                                             1
grover homes sec 4                                     1
4s aradhya homes                                       1
ansal api spanish court                                1
central park flower valley cerise floors               1
floor wise designer kothi                              1
birla navya                                            1
kothi                                                  1
rajendra park sec 105                                  1
ansal heights                                          1
landmark house                                         1
dlf the arbour                                         1
ansal florence super                                   1
cloudnine cottages                                     1
u block dlf phase 3 road no 21                         1
sector 15 part 2 rwa                                   1
nitin vihar                                            1
ansal                                                  1
ashok vihar phase iii extension                        1
rattan vihar rajendra park                             1
signature global city 63a                              1
dlf city plot phase 3                                  1
adani brahma samsara                                   1
sneh vihar                                             1
secter 16a daultabad faridabad house no 313            1
unitech south city                                     1
smart world orchard                                    1
suncity avenue 76                                      1
huda floor                                             1
huda                                                   1
private house                                          1
sector 57 huda                                         1
godrej meridien                                        1
ansal sushant lok 2                                    1
the laburnum                                           1
vatika independent floors                              1
arjun marg/ sector- 26 phase- 1/ golf course road      1
sector-17c                                             1
dlf pink town house                                    1
patel nager house no 927/5                             1
satya the legend                                       1
huda sector-56 gurgaon                                 1
independent house sector 45                            1
ashok vihar phase 3 gurgaon                            1
farrukhnagar                                           1
unitech greenwood city                                 1
vatika the seven lamps                                 1
ansal sushant lok                                      1
central park                                           1
signature global city 81                               1
signature global city                                  1
dlf floors phase 3                                     1
prem kunj                                              1
sheetla enclave                                        1
ss omnia                                               1
dlf garden city floors                                 1
mian wali                                              1
ansal celebrity homes                                  1
laxmi garden sector-11                                 1
huda housing board colony                              1
house number b-34                                      1
shree krishna homes                                    1
smart world gems                                       1
ganpati heights apartment                              1
hero homes                                             1
jacobpura gurugram                                     1
anand garden, sector-105                               1
ats tourmaline                                         1
rk excelo                                              1
dlf the grove                                          1
surendra homes dayanand colony                         1
bhawani enclave                                        1
om nagar, sector-11                                    1
all punjabi welfare association                        1
vatika sovereign next                                  1
manohar nagar                                          1
laxman vihar phase 2                                   1
anamika enclave                                        1
bhim nagar, sector 6                                   1
emaar mgf the palm drive                               1
tulip ivory                                            1
huda plots                                             1
shri shyam residency                                   1
rajendra park gurgaon                                  1
anshul                                                 1
huda plot sector 38                                    1
sare crescent parc royal greens phase 1                1
signature global park                                  1
vipul world                                            1
greenopolis                                            1
ansal esencia sovereign floors                         1
nirmal enclave, maruti kunj road                       1
jacob pura                                             1
mahavir pura                                           1
raj villas                                             1
sector 37                                              1
shivaji nagar residential                              1
bhim nagar society                                     1
my home                                                1
anant raj manor villas                                 1
dlf city plot phase 4                                  1
sai kripa floors 5                                     1
naman residency                                        1
krishna palace                                         1
surat nagar phase 2                                    1
huda flats                                             1
jacobpura                                              1
indiabulls centrum park                                1
madan puri                                             1
dlf gardencity enclave                                 1
row house                                              1
tulip yellow                                           1
Name: count, dtype: int64

In [310]:
data1.sample(2)

,PROPERTY_NAME,SOCIETY,PRICE,RATE,AREA,AREAWITHTYPE,BEDROOM,BATHROOM,BALCONY,ADDITIONALROOM,ADDRESS,NOOFFLOOR,FACING,AGEPOSSESSION,NEARBYLOCATIONS,DESCRIPTION,FURNISHDETAILS,FEATURES,RATING
350,6 Bedroom House for sale in Ashok Vihar Phase ...,nan,1.5 Crore,"₹ 5,000/sq.ft.",(279 sq.m.) Built-up Area,Built Up area: 3000 (278.71 sq.m.),6 Bedrooms,1 Bathroom,No Balcony,NaN,"Ashok Vihar Phase 3 Extension, Ashok Vihar Pha...",1 Floors,NaN,0 to 1 Year Old,NaN,Best in class property available at ashok viha...,NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
859,12 Bedroom House for sale in DLF Phase 1,nan,10.5 Crore,"₹ 43,210/sq.ft.",(253 sq.m.) Plot Area,Plot area 302(252.51 sq.m.)Built Up area: 300 ...,12 Bedrooms,12 Bathrooms,3+ Balconies,"Servant Room,Pooja Room","Dlf Phase 1, DLF Phase 1, Gurgaon, Haryana",4 Floors,North-East,1 to 5 Year Old,"['Guru dronacharya metro station', 'Dlf phase ...","Dlf phase 1 very prime location , this buildin...","['1 Water Purifier', '20 Fan', '1 Exhaust Fan'...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [311]:
data1['PRICE'].value_counts()

PRICE
3.5 Crore           19
5.5 Crore           17
6.5 Crore           16
6 Crore             14
8 Crore             13
5 Crore             13
4.5 Crore           13
50 Lac              13
70 Lac              13
75 Lac              13
85 Lac              12
2.5 Crore           12
8.5 Crore           12
7 Crore             12
4 Crore             11
1.5 Crore           11
60 Lac              10
45 Lac              10
Price on Request    10
90 Lac              10
10 Crore            10
9 Crore             10
2.25 Crore          10
80 Lac               9
1.7 Crore            9
9.5 Crore            9
1.1 Crore            9
12 Crore             9
2 Crore              9
1.6 Crore            8
4.6 Crore            8
1 Crore              8
6.75 Crore           8
11 Crore             8
3.75 Crore           8
1.2 Crore            7
2.1 Crore            7
1.3 Crore            7
65 Lac               7
95 Lac               7
55 Lac               7
40 Lac               7
1.35 Crore           7
12.5 Crore           7
1.45 Crore           6
2.95 Crore           6
7.5 Crore            6
5.7 Crore            6
4.25 Crore           6
3.25 Crore           6
13.5 Crore           6
5.6 Crore            6
2.75 Crore           6
6.25 Crore           6
1.15 Crore           6
7.25 Crore           6
10.5 Crore           6
16 Crore             6
3.6 Crore            6
35 Lac               5
5.75 Crore           5
4.75 Crore           5
15 Crore             5
2.8 Crore            5
3 Crore              5
17 Crore             5
1.25 Crore           5
1.8 Crore            5
38 Lac               5
8.25 Crore           5
9.25 Crore           4
18 Crore             4
4.35 Crore           4
2.4 Crore            4
42 Lac               4
1.65 Crore           4
4.7 Crore            4
37 Lac               4
5.25 Crore           4
1.4 Crore            4
13 Crore             4
8.4 Crore            4
6.8 Crore            4
11.5 Crore           4
3.2 Crore            4
5.8 Crore            4
3.3 Crore            4
62 Lac               3
7.2 Crore            3
49 Lac               3
3.85 Crore           3
4.45 Crore           3
82 Lac               3
3.55 Crore           3
1.16 Crore           3
2.3 Crore            3
1.9 Crore            3
34 Lac               3
1.55 Crore           3
20 Crore             3
2.2 Crore            3
3.1 Crore            3
5.65 Crore           3
2.9 Crore            3
1.95 Crore           3
5.15 Crore           3
92 Lac               3
6.4 Crore            3
1.85 Crore           3
2.55 Crore           3
4.3 Crore            3
7.35 Crore           3
19 Crore             3
6.95 Crore           3
3.4 Crore            3
32 Lac               3
4.95 Crore           2
58 Lac               2
58.25 Lac            2
14 Crore             2
2.15 Crore           2
9.9 Crore            2
89 Lac               2
1.05 Crore           2
3.51 Crore           2
3.15 Crore           2
3.35 Crore           2
8.49 Crore           2
10.85 Crore          2
5.4 Crore            2
11.95 Crore          2
36 Lac               2
3.65 Crore           2
26 Crore             2
10.55 Crore          2
3.05 Crore           2
7.1 Crore            2
6.3 Crore            2
11.25 Crore          2
15.5 Crore           2
48 Lac               2
11.75 Crore          2
67 Lac               2
19.5 Crore           2
10.45 Crore          2
1.75 Crore           2
7.99 Crore           2
30 Lac               2
66 Lac               2
10.3 Crore           1
2.47 Crore           1
3.7 Crore            1
7.3 Crore            1
4.15 Crore           1
18.4 Crore           1
22 Crore             1
6.15 Crore           1
4.4 Crore            1
8.45 Crore           1
46.75 Lac            1
9.4 Crore            1
18.5 Crore           1
12.25 Crore          1
27.5 Crore           1
52.75 Lac            1
5.88 Crore           1
8.31 Crore           1
6.21 Crore           1
2.01 Crore           1
3.9 Crore            1
5.1 Crore            1
1.83 Crore           1
99 Lac               1
2.45 Crore           1
2.65 Crore           1
1.18 Crore           1
9.01 Crore           1
9.8 Crore            1
4.99 Crore           1
8.6 Crore            1
9.55 Crore           1
2.35 Crore           1
18.25 Crore          1
5.3 Crore            1
10.8 Crore           1
31.5 Crore           1
4.1 Crore            1
7.65 Crore           1
6.46 Crore           1
6.44 Crore           1
7.8 Crore            1
3.8 Crore            1
7.45 Crore           1
7.42 Crore           1
6.09 Crore           1
15.1 Crore           1
9.85 Crore           1
1.27 Crore           1
1.04 Crore           1
11.29 Crore          1
4.31 Crore           1
11.58 Crore          1
8.48 Crore           1
8.2 Crore            1
5.51 Crore           1
3.49 Crore           1
2.99 Crore           1
9.19 Crore           1
1.64 Crore           1
9.35 Crore           1
4.05 Crore           1
8.75 Crore           1
23 Crore             1
8.9 Crore            1
7.85 Crore           1
25 Crore             1
2.68 Crore           1
2.7 Crore            1
4.49 Crore           1
65.8 Lac             1
8.81 Crore           1
55.11 Lac            1
7.5 Lac              1
2.58 Crore           1
8.95 Crore           1
13.2 Crore           1
51 Lac               1
53 Lac               1
63 Lac               1
1.72 Crore           1
78 Lac               1
1.52 Crore           1
5.46 Crore           1
52 Lac               1
10.56 Crore          1
4.65 Crore           1
6.1 Crore            1
68 Lac               1
1.07 Crore           1
3.12 Crore           1
7.49 Crore           1
6.81 Crore           1
22 Lac               1
7.05 Crore           1
3.69 Crore           1
11.3 Crore           1
4.02 Crore           1
6.6 Crore            1
5.35 Crore           1
5.85 Crore           1
5.9 Crore            1
6.2 Crore            1
3.93 Crore           1
8.7 Crore            1
7.69 Crore           1
15.5 Lac             1
8.8 Crore            1
4.12 Crore           1
1.87 Crore           1
12.39 Crore          1
7.6 Crore            1
5.2 Crore            1
42.75 Lac            1
47 Lac               1
61 Lac               1
1.34 Crore           1
46 Lac               1
2.6 Crore            1
3.87 Crore           1
1.39 Crore           1
59 Lac               1
27 Lac               1
8.1 Crore            1
14.75 Crore          1
9.54 Crore           1
17.3 Crore           1
18.9 Crore           1
24 Crore             1
7.46 Crore           1
59.95 Lac            1
3.99 Crore           1
18.02 Crore          1
10.75 Crore          1
96 Lac               1
24 Lac               1
71 Lac               1
52.5 Lac             1
1.44 Crore           1
3.71 Crore           1
18 Lac               1
3.08 Crore           1
29 Lac               1
44 Lac               1
13 Lac               1
83 Lac               1
98 Lac               1
47.5 Lac             1
3.09 Crore           1
74 Lac               1
69 Lac               1
2.43 Crore           1
2.98 Crore           1
Name: count, dtype: int64

In [312]:
data1['PRICE'] = data1['PRICE'].astype('str')

In [313]:
def convert_to_crore(price):
    if 'Lac' in price:
        return float(price.split()[0]) / 100
    elif 'Crore' in price:
        return float(price.split()[0])
    else:
        return None

data1['PRICE'] = data1['PRICE'].apply(convert_to_crore)

In [314]:
data1.head(1)

,PROPERTY_NAME,SOCIETY,PRICE,RATE,AREA,AREAWITHTYPE,BEDROOM,BATHROOM,BALCONY,ADDITIONALROOM,ADDRESS,NOOFFLOOR,FACING,AGEPOSSESSION,NEARBYLOCATIONS,DESCRIPTION,FURNISHDETAILS,FEATURES,RATING
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."

In [315]:
data1['PRICE'] = data1['PRICE'].astype('float')

In [316]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   PROPERTY_NAME    1095 non-null   object
 1   SOCIETY          1095 non-null   object
 2   PRICE            958 non-null    float64
 3   RATE             1054 non-null   object
 4   AREA             1095 non-null   object
 5   AREAWITHTYPE     987 non-null    object
 6   BEDROOM          987 non-null    object
 7   BATHROOM         987 non-null    object
 8   BALCONY          987 non-null    object
 9   ADDITIONALROOM   589 non-null    object
 10  ADDRESS          1031 non-null   object
 11  NOOFFLOOR        967 non-null    object
 12  FACING           674 non-null    object
 13  AGEPOSSESSION    987 non-null    object
 14  NEARBYLOCATIONS  913 non-null    object
 15  DESCRIPTION      1036 non-null   object
 16  FURNISHDETAILS   743 non-null    object
 17  FEATURES         674 non-null    object
 18  RATING           907 non-null    object
dtypes: float64(1), object(18)
memory usage: 162.7+ KB

In [317]:
data1['RATE'].value_counts()

RATE
₹ 22,222/sq.ft.     14
₹ 11,111/sq.ft.     12
₹ 33,333/sq.ft.     11
₹ 10,000/sq.ft.     10
₹ 37,037/sq.ft.      7
₹ 13,333/sq.ft.      7
₹ 26,235/sq.ft.      6
₹ 26,667/sq.ft.      6
₹ 8,000/sq.ft.       6
₹ 31,481/sq.ft.      6
₹ 30,556/sq.ft.      6
₹ 23,333/sq.ft.      5
₹ 5,000/sq.ft.       5
₹ 9,444/sq.ft.       5
₹ 11,100/sq.ft.      5
₹ 8,889/sq.ft.       5
₹ 32,407/sq.ft.      5
₹ 23,148/sq.ft.      5
₹ 9,722/sq.ft.       4
₹ 35,000/sq.ft.      4
₹ 15,625/sq.ft.      4
₹ 21,605/sq.ft.      4
₹ 6,944/sq.ft.       4
₹ 18,889/sq.ft.      4
₹ 24,691/sq.ft.      4
₹ 25,000/sq.ft.      4
₹ 7,058/sq.ft.       4
₹ 34,722/sq.ft.      4
₹ 27,778/sq.ft.      4
₹ 100,000/sq.ft.     3
₹ 13,889/sq.ft.      3
₹ 24,500/sq.ft.      3
₹ 17,037/sq.ft.      3
₹ 10,556/sq.ft.      3
₹ 6,666/sq.ft.       3
₹ 9,259/sq.ft.       3
₹ 8,235/sq.ft.       3
₹ 44,444/sq.ft.      3
₹ 11,250/sq.ft.      3
₹ 20,000/sq.ft.      3
₹ 16,058/sq.ft.      3
₹ 12,222/sq.ft.      3
₹ 17,284/sq.ft.      3
₹ 60,000/sq.ft.      3
₹ 8,333/sq.ft.       3
₹ 12,000/sq.ft.      3
₹ 25,562/sq.ft.      3
₹ 23,457/sq.ft.      3
₹ 25,926/sq.ft.      3
₹ 7,500/sq.ft.       3
₹ 33,951/sq.ft.      3
₹ 36,111/sq.ft.      3
₹ 29,880/sq.ft.      3
₹ 8,444/sq.ft.       3
₹ 5,555/sq.ft.       3
₹ 32,222/sq.ft.      3
₹ 14,815/sq.ft.      3
₹ 15,555/sq.ft.      3
₹ 50,000/sq.ft.      3
₹ 45,833/sq.ft.      3
₹ 12,963/sq.ft.      2
₹ 20,635/sq.ft.      2
₹ 38,194/sq.ft.      2
₹ 26,852/sq.ft.      2
₹ 10,753/sq.ft.      2
₹ 59,259/sq.ft.      2
₹ 13,000/sq.ft.      2
₹ 21,242/sq.ft.      2
₹ 7,777/sq.ft.       2
₹ 35,185/sq.ft.      2
₹ 24,845/sq.ft.      2
₹ 12,500/sq.ft.      2
₹ 26,389/sq.ft.      2
₹ 29,630/sq.ft.      2
₹ 4,444/sq.ft.       2
₹ 9,000/sq.ft.       2
₹ 17,778/sq.ft.      2
₹ 42,222/sq.ft.      2
₹ 35,556/sq.ft.      2
₹ 7,407/sq.ft.       2
₹ 3,500/sq.ft.       2
₹ 38,580/sq.ft.      2
₹ 10,783/sq.ft.      2
₹ 24,306/sq.ft.      2
₹ 12,342/sq.ft.      2
₹ 75,000/sq.ft.      2
₹ 7,619/sq.ft.       2
₹ 21,759/sq.ft.      2
₹ 3,857/sq.ft.       2
₹ 9,634/sq.ft.       2
₹ 5,333/sq.ft.       2
₹ 24,155/sq.ft.      2
₹ 27,461/sq.ft.      2
₹ 11,852/sq.ft.      2
₹ 10,518/sq.ft.      2
₹ 12,444/sq.ft.      2
₹ 37,627/sq.ft.      2
₹ 8,888/sq.ft.       2
₹ 39,841/sq.ft.      2
₹ 15,257/sq.ft.      2
₹ 20,833/sq.ft.      2
₹ 55,000/sq.ft.      2
₹ 32,328/sq.ft.      2
₹ 11,574/sq.ft.      2
₹ 37,777/sq.ft.      2
₹ 15,700/sq.ft.      2
₹ 16,975/sq.ft.      2
₹ 16,378/sq.ft.      2
₹ 42,194/sq.ft.      2
₹ 19,708/sq.ft.      2
₹ 16,039/sq.ft.      2
₹ 21,124/sq.ft.      2
₹ 17,187/sq.ft.      2
₹ 12,519/sq.ft.      2
₹ 32,963/sq.ft.      2
₹ 27,971/sq.ft.      2
₹ 19,000/sq.ft.      2
₹ 201,388/sq.ft.     2
₹ 21,000/sq.ft.      2
₹ 7,718/sq.ft.       2
₹ 15,278/sq.ft.      2
₹ 25,535/sq.ft.      2
₹ 38,095/sq.ft.      2
₹ 38,760/sq.ft.      2
₹ 1,859/sq.ft.       2
₹ 29,716/sq.ft.      2
₹ 10,579/sq.ft.      2
₹ 10,101/sq.ft.      2
₹ 12,027/sq.ft.      2
₹ 48,148/sq.ft.      2
₹ 13,910/sq.ft.      2
₹ 14,444/sq.ft.      2
₹ 20,690/sq.ft.      2
₹ 13,622/sq.ft.      2
₹ 18,928/sq.ft.      2
₹ 1,560/sq.ft.       1
₹ 42,054/sq.ft.      1
₹ 15,437/sq.ft.      1
₹ 11,240/sq.ft.      1
₹ 36,911/sq.ft.      1
₹ 15,444/sq.ft.      1
₹ 20,566/sq.ft.      1
₹ 8,866/sq.ft.       1
₹ 20,741/sq.ft.      1
₹ 11,102/sq.ft.      1
₹ 21,495/sq.ft.      1
₹ 18,444/sq.ft.      1
₹ 14,351/sq.ft.      1
₹ 27,191/sq.ft.      1
₹ 34,351/sq.ft.      1
₹ 11,157/sq.ft.      1
₹ 241,666/sq.ft.     1
₹ 47,803/sq.ft.      1
₹ 6,230/sq.ft.       1
₹ 13,492/sq.ft.      1
₹ 11,600/sq.ft.      1
₹ 33,665/sq.ft.      1
₹ 33,592/sq.ft.      1
₹ 24,455/sq.ft.      1
₹ 194,444/sq.ft.     1
₹ 290,948/sq.ft.     1
₹ 18,888/sq.ft.      1
₹ 13,178/sq.ft.      1
₹ 16,569/sq.ft.      1
₹ 23,061/sq.ft.      1
₹ 17,662/sq.ft.      1
₹ 51,440/sq.ft.      1
₹ 16,071/sq.ft.      1
₹ 23,240/sq.ft.      1
₹ 33,404/sq.ft.      1
₹ 20,068/sq.ft.      1
₹ 32,870/sq.ft.      1
₹ 26,428/sq.ft.      1
₹ 32,562/sq.ft.      1
₹ 22,429/sq.ft.      1
₹ 39,530/sq.ft.      1
₹ 38,889/sq.ft.      1
₹ 57,206/sq.ft.      1
₹ 27,222/sq.ft.      1
₹ 63,554/sq.ft.      1
₹ 31,686/sq.ft.      1
₹ 178,571/sq.ft.     1
₹ 261,194/sq.ft.     1
₹ 22,812/sq.ft.      1
₹ 82,540/sq.ft.      1
₹ 31,915/sq.ft.      1
₹ 34,491/sq.ft.      1
₹ 13,501/sq.ft.      1
₹ 28,782/sq.ft.      1
₹ 20,988/sq.ft.      1
₹ 400,000/sq.ft.     1
₹ 21,296/sq.ft.      1
₹ 18,626/sq.ft.      1
₹ 24,366/sq.ft.      1
₹ 26,298/sq.ft.      1
₹ 24,171/sq.ft.      1
₹ 23,000/sq.ft.      1
₹ 29,697/sq.ft.      1
₹ 6,778/sq.ft.       1
₹ 20,349/sq.ft.      1
₹ 38,734/sq.ft.      1
₹ 10,260/sq.ft.      1
₹ 12,551/sq.ft.      1
₹ 13,992/sq.ft.      1
₹ 28,898/sq.ft.      1
₹ 28,200/sq.ft.      1
₹ 7,168/sq.ft.       1
₹ 20,444/sq.ft.      1
₹ 33,129/sq.ft.      1
₹ 6,289/sq.ft.       1
₹ 17,857/sq.ft.      1
₹ 7,000/sq.ft.       1
₹ 10,067/sq.ft.      1
₹ 14,166/sq.ft.      1
₹ 30,968/sq.ft.      1
₹ 18,658/sq.ft.      1
₹ 10,484/sq.ft.      1
₹ 160,000/sq.ft.     1
₹ 8,127/sq.ft.       1
₹ 28,787/sq.ft.      1
₹ 7,555/sq.ft.       1
₹ 1,649/sq.ft.       1
₹ 7,539/sq.ft.       1
₹ 23,889/sq.ft.      1
₹ 9,210/sq.ft.       1
₹ 7,727/sq.ft.       1
₹ 45,710/sq.ft.      1
₹ 8,702/sq.ft.       1
₹ 5,950/sq.ft.       1
₹ 26,973/sq.ft.      1
₹ 13,750/sq.ft.      1
₹ 6,000/sq.ft.       1
₹ 14,890/sq.ft.      1
₹ 6,800/sq.ft.       1
₹ 31,008/sq.ft.      1
₹ 7,333/sq.ft.       1
₹ 8,101/sq.ft.       1
₹ 14,184/sq.ft.      1
₹ 4,260/sq.ft.       1
₹ 10,582/sq.ft.      1
₹ 9,390/sq.ft.       1
₹ 84,000/sq.ft.      1
₹ 6,938/sq.ft.       1
₹ 49,500/sq.ft.      1
₹ 13,030/sq.ft.      1
₹ 308,333/sq.ft.     1
₹ 14,285/sq.ft.      1
₹ 25,463/sq.ft.      1
₹ 7,007/sq.ft.       1
₹ 8,920/sq.ft.       1
₹ 35,294/sq.ft.      1
₹ 8,254/sq.ft.       1
₹ 5,128/sq.ft.       1
₹ 5,777/sq.ft.       1
₹ 15,926/sq.ft.      1
₹ 34,307/sq.ft.      1
₹ 10,610/sq.ft.      1
₹ 51,864/sq.ft.      1
₹ 44,265/sq.ft.      1
₹ 29,444/sq.ft.      1
₹ 39,074/sq.ft.      1
₹ 20,940/sq.ft.      1
₹ 23,442/sq.ft.      1
₹ 41,833/sq.ft.      1
₹ 600,000/sq.ft.     1
₹ 5,093/sq.ft.       1
₹ 19,737/sq.ft.      1
₹ 17,980/sq.ft.      1
₹ 10,740/sq.ft.      1
₹ 7,302/sq.ft.       1
₹ 8,155/sq.ft.       1
₹ 10,591/sq.ft.      1
₹ 24,074/sq.ft.      1
₹ 20,026/sq.ft.      1
₹ 5,160/sq.ft.       1
₹ 144,444/sq.ft.     1
₹ 9,615/sq.ft.       1
₹ 6,813/sq.ft.       1
₹ 15,046/sq.ft.      1
₹ 11,583/sq.ft.      1
₹ 6,034/sq.ft.       1
₹ 10,085/sq.ft.      1
₹ 40,611/sq.ft.      1
₹ 23,870/sq.ft.      1
₹ 29,629/sq.ft.      1
₹ 24,202/sq.ft.      1
₹ 10,601/sq.ft.      1
₹ 2,716/sq.ft.       1
₹ 24,005/sq.ft.      1
₹ 24,510/sq.ft.      1
₹ 8,137/sq.ft.       1
₹ 7,582/sq.ft.       1
₹ 18,605/sq.ft.      1
₹ 16,066/sq.ft.      1
₹ 55,556/sq.ft.      1
₹ 38,986/sq.ft.      1
₹ 266,666/sq.ft.     1
₹ 11,428/sq.ft.      1
₹ 29,638/sq.ft.      1
₹ 14,000/sq.ft.      1
₹ 22,184/sq.ft.      1
₹ 30,247/sq.ft.      1
₹ 18,814/sq.ft.      1
₹ 20,370/sq.ft.      1
₹ 31,666/sq.ft.      1
₹ 283,333/sq.ft.     1
₹ 26,502/sq.ft.      1
₹ 18,808/sq.ft.      1
₹ 32,253/sq.ft.      1
₹ 29,074/sq.ft.      1
₹ 34,568/sq.ft.      1
₹ 21,097/sq.ft.      1
₹ 25,556/sq.ft.      1
₹ 7,756/sq.ft.       1
₹ 21,825/sq.ft.      1
₹ 16,577/sq.ft.      1
₹ 17,706/sq.ft.      1
₹ 19,847/sq.ft.      1
₹ 7,172/sq.ft.       1
₹ 10,838/sq.ft.      1
₹ 37,778/sq.ft.      1
₹ 31,111/sq.ft.      1
₹ 17,213/sq.ft.      1
₹ 18,620/sq.ft.      1
₹ 17,014/sq.ft.      1
₹ 7,750/sq.ft.       1
₹ 18,008/sq.ft.      1
₹ 12,285/sq.ft.      1
₹ 19,293/sq.ft.      1
₹ 18,088/sq.ft.      1
₹ 23,504/sq.ft.      1
₹ 234,375/sq.ft.     1
₹ 21,786/sq.ft.      1
₹ 15,432/sq.ft.      1
₹ 21,251/sq.ft.      1
₹ 27,160/sq.ft.      1
₹ 16,600/sq.ft.      1
₹ 35,530/sq.ft.      1
₹ 15,000/sq.ft.      1
₹ 20,317/sq.ft.      1
₹ 22,046/sq.ft.      1
₹ 27,132/sq.ft.      1
₹ 22,855/sq.ft.      1
₹ 40,741/sq.ft.      1
₹ 22,331/sq.ft.      1
₹ 29,333/sq.ft.      1
₹ 21,219/sq.ft.      1
₹ 9,349/sq.ft.       1
₹ 3,786/sq.ft.       1
₹ 41,315/sq.ft.      1
₹ 20,599/sq.ft.      1
₹ 173,992/sq.ft.     1
₹ 21,367/sq.ft.      1
₹ 20,299/sq.ft.      1
₹ 41,818/sq.ft.      1
₹ 19,231/sq.ft.      1
₹ 6,875/sq.ft.       1
₹ 18,885/sq.ft.      1
₹ 14,667/sq.ft.      1
₹ 14,787/sq.ft.      1
₹ 19,125/sq.ft.      1
₹ 16,319/sq.ft.      1
₹ 18,250/sq.ft.      1
₹ 27,390/sq.ft.      1
₹ 30,728/sq.ft.      1
₹ 20,769/sq.ft.      1
₹ 13,513/sq.ft.      1
₹ 28,549/sq.ft.      1
₹ 6,849/sq.ft.       1
₹ 30,864/sq.ft.      1
₹ 161,849/sq.ft.     1
₹ 16,056/sq.ft.      1
₹ 17,707/sq.ft.      1
₹ 10,926/sq.ft.      1
₹ 19,608/sq.ft.      1
₹ 8,089/sq.ft.       1
₹ 19,607/sq.ft.      1
₹ 29,022/sq.ft.      1
₹ 40,000/sq.ft.      1
₹ 34,846/sq.ft.      1
₹ 31,444/sq.ft.      1
₹ 27,083/sq.ft.      1
₹ 43,210/sq.ft.      1
₹ 31,926/sq.ft.      1
₹ 38,611/sq.ft.      1
₹ 17,624/sq.ft.      1
₹ 27,333/sq.ft.      1
₹ 16,004/sq.ft.      1
₹ 29,293/sq.ft.      1
₹ 23,704/sq.ft.      1
₹ 23,693/sq.ft.      1
₹ 24,573/sq.ft.      1
₹ 15,989/sq.ft.      1
₹ 23,932/sq.ft.      1
₹ 19,268/sq.ft.      1
₹ 19,360/sq.ft.      1
₹ 79,365/sq.ft.      1
₹ 26,063/sq.ft.      1
₹ 23,437/sq.ft.      1
₹ 12,393/sq.ft.      1
₹ 40,850/sq.ft.      1
₹ 26,111/sq.ft.      1
₹ 31,790/sq.ft.      1
₹ 235,376/sq.ft.     1
₹ 27,911/sq.ft.      1
₹ 12,837/sq.ft.      1
₹ 12,037/sq.ft.      1
₹ 11,666/sq.ft.      1
₹ 17,692/sq.ft.      1
₹ 38,022/sq.ft.      1
₹ 25,309/sq.ft.      1
₹ 16,990/sq.ft.      1
₹ 14,222/sq.ft.      1
₹ 16,388/sq.ft.      1
₹ 22,075/sq.ft.      1
₹ 47,167/sq.ft.      1
₹ 12,198/sq.ft.      1
₹ 7,937/sq.ft.       1
₹ 20,197/sq.ft.      1
₹ 34,037/sq.ft.      1
₹ 10,123/sq.ft.      1
₹ 24,390/sq.ft.      1
₹ 17,820/sq.ft.      1
₹ 28,858/sq.ft.      1
₹ 35,109/sq.ft.      1
₹ 27,871/sq.ft.      1
₹ 36,883/sq.ft.      1
₹ 19,645/sq.ft.      1
₹ 35,741/sq.ft.      1
₹ 16,666/sq.ft.      1
₹ 7,827/sq.ft.       1
₹ 23,556/sq.ft.      1
₹ 10,035/sq.ft.      1
₹ 28,841/sq.ft.      1
₹ 26,615/sq.ft.      1
₹ 62,222/sq.ft.      1
₹ 16,003/sq.ft.      1
₹ 6,597/sq.ft.       1
₹ 7,870/sq.ft.       1
₹ 28,233/sq.ft.      1
₹ 15,111/sq.ft.      1
₹ 19,820/sq.ft.      1
₹ 1,087/sq.ft.       1
₹ 9,103/sq.ft.       1
₹ 20,115/sq.ft.      1
₹ 7,400/sq.ft.       1
₹ 4,666/sq.ft.       1
₹ 40,775/sq.ft.      1
₹ 99,173/sq.ft.      1
₹ 6,172/sq.ft.       1
₹ 9,111/sq.ft.       1
₹ 80,357/sq.ft.      1
₹ 4,117/sq.ft.       1
₹ 7,308/sq.ft.       1
₹ 8,701/sq.ft.       1
₹ 2,296/sq.ft.       1
₹ 9,793/sq.ft.       1
₹ 6,250/sq.ft.       1
₹ 8,486/sq.ft.       1
₹ 11,717/sq.ft.      1
₹ 7,589/sq.ft.       1
₹ 12,592/sq.ft.      1
₹ 15,384/sq.ft.      1
₹ 7,843/sq.ft.       1
₹ 7,778/sq.ft.       1
₹ 7,666/sq.ft.       1
₹ 102,941/sq.ft.     1
₹ 138,888/sq.ft.     1
₹ 24,912/sq.ft.      1
₹ 255,555/sq.ft.     1
₹ 4,333/sq.ft.       1
₹ 11,784/sq.ft.      1
₹ 13,359/sq.ft.      1
₹ 197,080/sq.ft.     1
₹ 13,131/sq.ft.      1
₹ 74,074/sq.ft.      1
₹ 10,233/sq.ft.      1
₹ 8,878/sq.ft.       1
₹ 14,286/sq.ft.      1
₹ 8,928/sq.ft.       1
₹ 8,007/sq.ft.       1
₹ 5,698/sq.ft.       1
₹ 28,283/sq.ft.      1
₹ 24,214/sq.ft.      1
₹ 26,613/sq.ft.      1
₹ 29,336/sq.ft.      1
₹ 10,288/sq.ft.      1
₹ 11,284/sq.ft.      1
₹ 11,029/sq.ft.      1
₹ 57,692/sq.ft.      1
₹ 10,482/sq.ft.      1
₹ 25,386/sq.ft.      1
₹ 8,735/sq.ft.       1
₹ 18,667/sq.ft.      1
₹ 2,525/sq.ft.       1
₹ 17,695/sq.ft.      1
₹ 21,519/sq.ft.      1
₹ 17,817/sq.ft.      1
₹ 2/sq.ft.           1
₹ 6,173/sq.ft.       1
₹ 13,888/sq.ft.      1
₹ 20,323/sq.ft.      1
₹ 20,359/sq.ft.      1
₹ 5,833/sq.ft.       1
₹ 11,693/sq.ft.      1
₹ 53,125/sq.ft.      1
₹ 5,472/sq.ft.       1
₹ 20,425/sq.ft.      1
₹ 21,667/sq.ft.      1
₹ 230,547/sq.ft.     1
₹ 10,277/sq.ft.      1
₹ 8,518/sq.ft.       1
₹ 10,555/sq.ft.      1
₹ 557/sq.ft.         1
₹ 8,947/sq.ft.       1
₹ 39,265/sq.ft.      1
₹ 6,083/sq.ft.       1
₹ 8,411/sq.ft.       1
₹ 9,333/sq.ft.       1
₹ 32,291/sq.ft.      1
₹ 41,666/sq.ft.      1
₹ 7,280/sq.ft.       1
₹ 90,000/sq.ft.      1
₹ 10,089/sq.ft.      1
₹ 8,697/sq.ft.       1
₹ 8,500/sq.ft.       1
₹ 29,321/sq.ft.      1
₹ 13,071/sq.ft.      1
₹ 39,886/sq.ft.      1
₹ 122,222/sq.ft.     1
₹ 19,097/sq.ft.      1
₹ 7,290/sq.ft.       1
₹ 27,741/sq.ft.      1
₹ 43,534/sq.ft.      1
₹ 45,889/sq.ft.      1
₹ 13,909/sq.ft.      1
₹ 35,400/sq.ft.      1
₹ 13,623/sq.ft.      1
₹ 13,331/sq.ft.      1
₹ 40,135/sq.ft.      1
₹ 16,244/sq.ft.      1
₹ 16,999/sq.ft.      1
₹ 10,714/sq.ft.      1
₹ 10,463/sq.ft.      1
₹ 18,750/sq.ft.      1
₹ 27,793/sq.ft.      1
₹ 22,006/sq.ft.      1
₹ 13,542/sq.ft.      1
₹ 28,490/sq.ft.      1
₹ 24,444/sq.ft.      1
₹ 24,170/sq.ft.      1
₹ 38,251/sq.ft.      1
₹ 43,066/sq.ft.      1
₹ 53,763/sq.ft.      1
₹ 39,062/sq.ft.      1
₹ 48,889/sq.ft.      1
₹ 38,150/sq.ft.      1
₹ 10,077/sq.ft.      1
₹ 34,083/sq.ft.      1
₹ 33,200/sq.ft.      1
₹ 14,914/sq.ft.      1
₹ 29,861/sq.ft.      1
₹ 41,762/sq.ft.      1
₹ 15,451/sq.ft.      1
₹ 12,938/sq.ft.      1
₹ 9,374/sq.ft.       1
₹ 13,410/sq.ft.      1
₹ 32,593/sq.ft.      1
₹ 28,760/sq.ft.      1
₹ 41,615/sq.ft.      1
₹ 38,703/sq.ft.      1
₹ 12,828/sq.ft.      1
₹ 86,567/sq.ft.      1
₹ 92,857/sq.ft.      1
₹ 88,157/sq.ft.      1
₹ 29,974/sq.ft.      1
₹ 2,778/sq.ft.       1
₹ 46,906/sq.ft.      1
₹ 23,699/sq.ft.      1
₹ 25,960/sq.ft.      1
₹ 28,424/sq.ft.      1
₹ 4,490/sq.ft.       1
₹ 14,729/sq.ft.      1
₹ 25,111/sq.ft.      1
₹ 7,309/sq.ft.       1
₹ 8,181/sq.ft.       1
₹ 43,333/sq.ft.      1
₹ 481/sq.ft.         1
₹ 3,452/sq.ft.       1
₹ 630/sq.ft.         1
₹ 4,074/sq.ft.       1
₹ 9,028/sq.ft.       1
₹ 13,778/sq.ft.      1
₹ 12,842/sq.ft.      1
₹ 8,557/sq.ft.       1
₹ 16,428/sq.ft.      1
₹ 13,519/sq.ft.      1
₹ 42,032/sq.ft.      1
₹ 24,069/sq.ft.      1
₹ 14,650/sq.ft.      1
₹ 21,250/sq.ft.      1
₹ 36,667/sq.ft.      1
₹ 38,667/sq.ft.      1
₹ 12,593/sq.ft.      1
₹ 25,514/sq.ft.      1
₹ 17,650/sq.ft.      1
₹ 24,280/sq.ft.      1
₹ 26,423/sq.ft.      1
₹ 8,916/sq.ft.       1
₹ 17,900/sq.ft.      1
₹ 126,865/sq.ft.     1
₹ 7,479/sq.ft.       1
₹ 8,012/sq.ft.       1
₹ 10,142/sq.ft.      1
₹ 8,125/sq.ft.       1
₹ 14,583/sq.ft.      1
₹ 11,538/sq.ft.      1
₹ 8,730/sq.ft.       1
₹ 105,751/sq.ft.     1
₹ 8,230/sq.ft.       1
₹ 13,095/sq.ft.      1
₹ 29,311/sq.ft.      1
₹ 30,384/sq.ft.      1
₹ 19,818/sq.ft.      1
₹ 1,992/sq.ft.       1
₹ 98,214/sq.ft.      1
₹ 13,499/sq.ft.      1
₹ 7,820/sq.ft.       1
₹ 4,000/sq.ft.       1
₹ 14,720/sq.ft.      1
₹ 183,333/sq.ft.     1
₹ 7,111/sq.ft.       1
₹ 32,258/sq.ft.      1
₹ 9,135/sq.ft.       1
₹ 31,506/sq.ft.      1
₹ 12,820/sq.ft.      1
₹ 229,885/sq.ft.     1
₹ 12,400/sq.ft.      1
₹ 232/sq.ft.         1
₹ 218,750/sq.ft.     1
₹ 54,794/sq.ft.      1
₹ 14,245/sq.ft.      1
₹ 6,367/sq.ft.       1
₹ 37,313/sq.ft.      1
₹ 90,909/sq.ft.      1
₹ 10,122/sq.ft.      1
₹ 8,642/sq.ft.       1
₹ 6,481/sq.ft.       1
₹ 6,707/sq.ft.       1
₹ 245,398/sq.ft.     1
₹ 11,904/sq.ft.      1
₹ 5,664/sq.ft.       1
₹ 19,753/sq.ft.      1
₹ 76,000/sq.ft.      1
₹ 63,492/sq.ft.      1
₹ 3,254/sq.ft.       1
₹ 4,583/sq.ft.       1
₹ 21,875/sq.ft.      1
₹ 16,667/sq.ft.      1
₹ 7,075/sq.ft.       1
₹ 8,078/sq.ft.       1
₹ 4,251/sq.ft.       1
₹ 17,584/sq.ft.      1
₹ 5,397/sq.ft.       1
₹ 9,074/sq.ft.       1
₹ 5,583/sq.ft.       1
₹ 3,519/sq.ft.       1
₹ 11,194/sq.ft.      1
₹ 6,981/sq.ft.       1
₹ 6,702/sq.ft.       1
₹ 18,333/sq.ft.      1
₹ 4,877/sq.ft.       1
₹ 17,937/sq.ft.      1
₹ 9,500/sq.ft.       1
₹ 26,620/sq.ft.      1
₹ 20,062/sq.ft.      1
₹ 2,500/sq.ft.       1
₹ 6,667/sq.ft.       1
₹ 3,704/sq.ft.       1
₹ 12,777/sq.ft.      1
₹ 6,648/sq.ft.       1
₹ 11,407/sq.ft.      1
₹ 20,233/sq.ft.      1
₹ 11,494/sq.ft.      1
₹ 181,818/sq.ft.     1
₹ 25,543/sq.ft.      1
₹ 12,343/sq.ft.      1
₹ 16,892/sq.ft.      1
₹ 17,500/sq.ft.      1
₹ 3,904/sq.ft.       1
₹ 14,323/sq.ft.      1
₹ 4,222/sq.ft.       1
₹ 16,389/sq.ft.      1
₹ 11,888/sq.ft.      1
₹ 40,909/sq.ft.      1
₹ 15,097/sq.ft.      1
₹ 9,375/sq.ft.       1
₹ 4,400/sq.ft.       1
₹ 13,636/sq.ft.      1
₹ 28,674/sq.ft.      1
₹ 9,725/sq.ft.       1
₹ 21,111/sq.ft.      1
₹ 10,784/sq.ft.      1
₹ 12,162/sq.ft.      1
₹ 8,910/sq.ft.       1
₹ 19,869/sq.ft.      1
₹ 8,796/sq.ft.       1
₹ 7,522/sq.ft.       1
₹ 5,658/sq.ft.       1
₹ 24,545/sq.ft.      1
₹ 7,701/sq.ft.       1
₹ 14,072/sq.ft.      1
₹ 26,000/sq.ft.      1
₹ 10,134/sq.ft.      1
₹ 12,778/sq.ft.      1
₹ 10,378/sq.ft.      1
₹ 8,386/sq.ft.       1
₹ 27,155/sq.ft.      1
₹ 14,492/sq.ft.      1
₹ 14,045/sq.ft.      1
₹ 10,804/sq.ft.      1
₹ 14,167/sq.ft.      1
₹ 13,157/sq.ft.      1
₹ 5,888/sq.ft.       1
₹ 7,875/sq.ft.       1
₹ 9,654/sq.ft.       1
₹ 4,808/sq.ft.       1
₹ 8,222/sq.ft.       1
₹ 11,273/sq.ft.      1
₹ 7,627/sq.ft.       1
₹ 5,666/sq.ft.       1
₹ 6,567/sq.ft.       1
₹ 22,068/sq.ft.      1
₹ 66,666/sq.ft.      1
₹ 24,305/sq.ft.      1
₹ 19,286/sq.ft.      1
₹ 22,634/sq.ft.      1
₹ 26,570/sq.ft.      1
₹ 17,574/sq.ft.      1
₹ 9,091/sq.ft.       1
₹ 23,557/sq.ft.      1
₹ 105,263/sq.ft.     1
₹ 21,195/sq.ft.      1
₹ 151/sq.ft.         1
₹ 25,103/sq.ft.      1
₹ 14,954/sq.ft.      1
₹ 8,784/sq.ft.       1
₹ 6,500/sq.ft.       1
₹ 35,494/sq.ft.      1
₹ 11,464/sq.ft.      1
₹ 11,718/sq.ft.      1
₹ 11,555/sq.ft.      1
₹ 3,874/sq.ft.       1
₹ 7,576/sq.ft.       1
₹ 11,556/sq.ft.      1
₹ 23,662/sq.ft.      1
₹ 27,139/sq.ft.      1
₹ 74,000/sq.ft.      1
₹ 211,111/sq.ft.     1
₹ 6,410/sq.ft.       1
₹ 133,079/sq.ft.     1
₹ 5,778/sq.ft.       1
₹ 6,111/sq.ft.       1
₹ 78,125/sq.ft.      1
₹ 17,955/sq.ft.      1
₹ 7,916/sq.ft.       1
₹ 80,000/sq.ft.      1
₹ 3,285/sq.ft.       1
₹ 120,000/sq.ft.     1
₹ 22,297/sq.ft.      1
₹ 125,000/sq.ft.     1
₹ 73,333/sq.ft.      1
₹ 6,790/sq.ft.       1
₹ 315,789/sq.ft.     1
₹ 10,224/sq.ft.      1
₹ 13,034/sq.ft.      1
Name: count, dtype: int64

In [318]:
data1['RATE'] = data1['RATE'].str.split("/").str.get(0).str.replace('₹'," ").str.replace(",","").str.replace(" ","").str.strip()

In [319]:
data1['RATE']

0        20115
1       105751
2        38251
3        43066
4        53763
5        39062
6        37037
7        48889
8        38150
9        10077
10       32963
11       27778
12       34083
13       33200
14       30556
15       14914
16       29861
17       23333
18       41762
19       15451
20       12938
21       38095
22       25926
23       26235
24       38760
25       25926
26        9374
27       13410
28       21124
29       32593
30       24170
31       37037
32       28490
33      122222
34       13542
35       19097
36       48148
37       22222
38       22222
39       33333
40       32222
41        7290
42       27741
43       50000
44       43534
45       45889
46       34722
47         NaN
48       20690
49       29716
50       16378
51       17284
52       37777
53       12519
54       25562
55       27971
56       21000
57       24500
58        7058
59        7058
60        7718
61       25535
62        1859
63       17037
64       10579
65       42194
66       15625
67       15278
68      201388
69       17187
70         NaN
71       44444
72       18928
73       11250
74       23333
75       13622
76       13909
77       20000
78       35400
79       16058
80       16058
81       13623
82       13910
83       13910
84       12027
85       15700
86       19708
87       16039
88       13331
89       11100
90       11100
91       11100
92       40135
93       16244
94       19708
95       16039
96       11100
97       11100
98       16999
99       10714
100      12027
101        NaN
102        NaN
103      21605
104      10463
105      18750
106      19000
107      27793
108      22006
109      19000
110      13333
111      22222
112      28760
113      16975
114      41615
115      16058
116      15700
117        NaN
118        NaN
119      14444
120      10101
121      38703
122      22222
123      12828
124      12842
125      23148
126       8557
127      16428
128        NaN
129      10556
130      13519
131      42032
132      24069
133      21605
134      13889
135      14650
136      13889
137      13778
138      15625
139      23333
140      21250
141      38667
142      26667
143      12593
144      26389
145      12963
146      25514
147      24845
148      17650
149      24280
150      26423
151       6666
152       8916
153      36667
154       9000
155      20000
156       9028
157       4074
158        630
159      86567
160      92857
161     100000
162      88157
163      29974
164      24691
165       2778
166      46906
167      25000
168      23699
169      25960
170      28424
171      33333
172       4490
173      14729
174      25111
175      25000
176       7309
177      10556
178      32407
179      37037
180       8181
181      43333
182       7777
183        481
184       3452
185      24444
186     100000
187      13071
188      11111
189     102941
190      29321
191      21242
192      24912
193     255555
194       9259
195       4333
196      11784
197      13359
198     197080
199      13131
200      74074
201      12000
202      10233
203      26852
204       8878
205      14286
206       8928
207       8007
208      11111
209       5698
210      28283
211      24214
212      26613
213     138888
214      10000
215       7666
216       7407
217       8333
218       4666
219      13333
220      60000
221      11111
222       7778
223      40775
224      99173
225      12222
226       6172
227      22222
228       9111
229      80357
230       4117
231       7308
232       8701
233       8000
234      25926
235       6666
236       2296
237       8888
238      33333
239      12444
240       9793
241       6250
242       8486
243      11717
244       7589
245      13333
246      12592
247      15384
248       7843
249      22222
250      23333
251      29336
252      10288
253      11284
254      11029
255      10277
256       6944
257       8518
258      10555
259      11250
260        557
261       8888
262      11852
263       8947
264      39265
265       6083
266     230547
267       8411
268      32291
269      41666
270       8889
271       7280
272      90000
273      10089
274       8697
275       8500
276       9333
277       8235
278      13333
279      21667
280      20425
281       5472
282       6944
283      57692
284      60000
285        NaN
286       3857
287      21759
288       8333
289       7407
290      75000
291      10482
292      25386
293       8735
294       9444
295        NaN
296        NaN
297      20000
298      18667
299      18889
300       2525
301      24306
302      17695
303      21519
304      17817
305          2
306       6173
307      55000
308        NaN
309      13888
310      20323
311      20359
312        NaN
313        NaN
314       5833
315      11693
316      26667
317      53125
318      17900
319        NaN
320      39886
321     126865
322      40909
323      27155
324      14492
325        NaN
326        NaN
327      13622
328      14045
329      10783
330      10804
331      10783
332      14167
333      11111
334        NaN
335      13157
336       5888
337      11111
338       7875
339       9654
340       4808
341       8222
342      11111
343       3857
344      50000
345      11273
346       8000
347       7627
348       5666
349       5000
350       5000
351       6567
352      22068
353      13333
354       6666
355      66666
356       7500
357       8386
358       7619
359       8000
360      12778
361        NaN
362       5333
363      15097
364      10134
365      27461
366       9375
367       4400
368      13333
369      13636
370      12444
371      25000
372       6944
373        NaN
374      11111
375      28674
376       9725
377      21111
378       7500
379      10784
380      12162
381       8910
382      10518
383      19869
384       8796
385       9722
386       7522
387       5658
388       5000
389      24545
390       7701
391       8235
392      14072
393      26000
394      24305
395      19286
396      22634
397      26570
398      11111
399       6410
400     133079
401      15257
402        NaN
403       5778
404       6111
405      15625
406      78125
407      17955
408       7916
409     211111
410      80000
411      35000
412      10000
413     120000
414      22297
415     125000
416       8889
417      73333
418        NaN
419      11111
420      26235
421       6790
422      20833
423     315789
424      10224
425       3500
426       3285
427      74000
428      27139
429      10000
430       5555
431        NaN
432      23662
433      17574
434      13333
435      10753
436       9091
437      23557
438      59259
439     105263
440      21195
441        151
442      25103
443      13889
444      14954
445      23333
446       8784
447       6500
448      35494
449      11464
450      11718
451      11555
452      50000
453       3874
454       7576
455      11556
456      10753
457      20635
458      10378
459      11888
460      17284
461      32258
462      11111
463      12222
464      16389
465      31506
466       9722
467      12820
468     229885
469      10000
470       8889
471      12400
472       9259
473        232
474      15257
475     218750
476      54794
477      14245
478       6367
479      37313
480      90909
481       9444
482       5000
483        NaN
484      10122
485      10000
486       8642
487       6481
488       6707
489     245398
490       9259
491        NaN
492      11904
493       9135
494        NaN
495       7111
496       8012
497     183333
498      12500
499      10142
500       8444
501       8125
502      14583
503      17037
504      11538
505       8730
506      12222
507      14444
508      11574
509        NaN
510      26667
511      11111
512       8230
513      13095
514      30556
515      11852
516      10000
517      29311
518      11250
519      30384
520       8444
521      19818
522       1992
523       7619
524      98214
525      13499
526       7820
527       5555
528       4000
529      14720
530       5664
531      19753
532      76000
533      37037
534      63492
535       9000
536       4444
537       2500
538       6667
539       3704
540      12777
541       6648
542      11407
543      20233
544      17778
545      20062
546      11494
547      25543
548      12343
549      16892
550       8000
551      17500
552       3904
553      14323
554       4222
555     181818
556      75000
557      26620
558       5555
559      10000
560       9722
561       9500
562      17937
563       3254
564       5333
565      30556
566       4583
567      12500
568      21875
569        NaN
570      16667
571       7075
572       8078
573       4251
574      17584
575       5397
576       9074
577       5583
578       3519
579      11194
580     100000
581       6981
582       6702
583       9444
584      10556
585      18333
586       4877
587       7479
588       7400
589      16003
590       8000
591       9444
592       9103
593       7727
594      45710
595        NaN
596       8702
597       5950
598       3500
599       9722
600       8889
601      26973
602      32407
603      13750
604       6000
605      14890
606       9210
607       6800
608      10518
609       7333
610       8101
611       6944
612      14184
613       4260
614      10582
615       9390
616      84000
617       6938
618      15555
619      33333
620       7539
621      10000
622      10067
623       1649
624      10000
625      10000
626      13000
627      28898
628      28200
629       7168
630      20444
631        NaN
632      35185
633       6289
634      17857
635       7000
636      14166
637      30968
638       7777
639      18658
640      10484
641     160000
642       8127
643       5000
644       8000
645       7555
646      49500
647       8889
648      13030
649     308333
650       8333
651      10610
652      18889
653       7302
654       8155
655      10591
656      24074
657      14815
658       5160
659     144444
660       9615
661       9444
662      10101
663      22222
664      32407
665       6813
666      15046
667      11583
668        NaN
669       6034
670      10085
671      17778
672      40611
673      29630
674      29629
675      10740
676       4444
677      17980
678      55000
679      19737
680       5093
681      25463
682      12000
683       7007
684       8920
685      35294
686      12963
687       8254
688       5128
689       5777
690      15926
691      11111
692      14285
693      34307
694      51864
695      44265
696      29444
697      39074
698      38734
699      23442
700      41833
701      27778
702     600000
703      23889
704      25000
705      10260
706      31915
707      11102
708       8866
709      36911
710      36111
711      15444
712      11240
713      15437
714      14351
715      27191
716     241666
717      32963
718      33592
719      24455
720      26667
721      26389
722     194444
723      18444
724      11600
725      38095
726      13492
727      33951
728      11157
729       8444
730      21495
731      42054
732       1560
733      20741
734      13178
735      12000
736      26428
737      82540
738      18888
739      31481
740      13501
741      20988
742     400000
743      21296
744      34722
745      18626
746      24366
747      26298
748       7500
749      24171
750      23000
751      29697
752      33333
753      36111
754       6778
755      22812
756     261194
757     178571
758      27461
759      31686
760      22222
761      23061
762      32222
763      17662
764      39841
765      37627
766      23148
767      29880
768      20068
769      16569
770      21242
771      11574
772      32562
773      13000
774      22429
775      39530
776      22222
777      38889
778        NaN
779      57206
780      27222
781      63554
782      10601
783      20940
784      32253
785      37037
786        NaN
787      23704
788      23693
789      15989
790      19268
791      19360
792      45833
793      29880
794      23437
795       2716
796      39841
797      32222
798      40850
799      12342
800      15555
801      26111
802      31790
803      24691
804     235376
805      29293
806      16004
807      27333
808      17624
809      38580
810      27778
811      35556
812      38580
813      35000
814      30864
815        NaN
816     161849
817      27778
818      16056
819      17707
820      20690
821      29716
822      16378
823      17284
824      37777
825      12519
826      25562
827      27971
828      21000
829      24500
830       7058
831       7058
832       7718
833      25535
834       1859
835      17037
836      10579
837      42194
838      15625
839      15278
840     201388
841      17187
842        NaN
843      44444
844      18928
845      10926
846      19608
847       8089
848       6849
849      24691
850        NaN
851      19607
852      40000
853      34846
854      31444
855      26235
856      22222
857      23457
858      27083
859      43210
860      31926
861      38611
862      27911
863      29022
864      12837
865      12198
866      35741
867        NaN
868      16666
869      35556
870       9634
871      45833
872      31481
873       7827
874      38760
875      23556
876      10035
877      28841
878      26615
879      24155
880      14815
881      22222
882      62222
883       6597
884       7870
885      26852
886      28233
887      15111
888      34722
889      19820
890       1087
891        NaN
892      31481
893      26235
894      19645
895      36883
896      37037
897      27871
898      35109
899      17692
900      38022
901      33333
902      25309
903      16990
904      14222
905      22222
906      16388
907      22075
908      11666
909      47167
910       7937
911      20197
912      20635
913      34037
914      10123
915      28858
916      28549
917      15555
918      13513
919      20769
920      34568
921      21097
922      33951
923      24306
924      25556
925      36111
926       7756
927      21825
928      12342
929      16577
930      17706
931      29074
932      29880
933      42222
934      38194
935      21605
936      38194
937      37778
938      31111
939      17213
940      18620
941      17014
942       7750
943       7172
944      29638
945      33333
946       8137
947       7582
948      48148
949      18605
950      16066
951      55556
952      38986
953      24510
954      11428
955      22184
956      30247
957      20370
958      31666
959      18889
960     283333
961      31481
962      42222
963      59259
964      45833
965      18008
966      26235
967        NaN
968      33333
969      12285
970      19293
971      20599
972     173992
973      21367
974      20299
975      41818
976       9634
977      19231
978      20833
979      33333
980       6875
981      14667
982      14787
983      16319
984      18250
985      27390
986      30728
987      35000
988      30556
989      41315
990       3786
991      60000
992      24691
993       9349
994      23504
995      21605
996     234375
997      26235
998      21786
999      35000
1000      8235
1001     15432
1002     37627
1003     21251
1004     30556
1005     27160
1006     35530
1007     22046
1008     22222
1009     33333
1010     27132
1011     22855
1012     40741
1013     34722
1014     29333
1015     32328
1016    290948
1017     25562
1018     12393
1019     22331
1020     20317
1021     18088
1022     21759
1023     16600
1024     21219
1025     19125
1026     18885
1027     15000
1028     37037
1029     18814
1030     32328
1031     23457
1032     16975
1033     18889
1034     14000
1035     32407
1036    266666
1037     26502
1038     23148
1039     32407
1040     33951
1041     18808
1042     31481
1043     10838
1044     19847
1045     23148
1046     12037
1047     17820
1048     24390
1049     35185
1050       NaN
1051     26063
1052     79365
1053     23932
1054     24573
1055     24005
1056     32870
1057     33404
1058     23240
1059     29630
1060     16071
1061     51440
1062     26667
1063     28782
1064     34491
1065     34351
1066     47803
1067      6230
1068     33665
1069     44444
1070       NaN
1071       NaN
1072     20566
1073     22222
1074     26667
1075     20349
1076     23148
1077     21124
1078     24202
1079     24155
1080     23870
1081     24500
1082     24845
1083     20026
1084     28787
1085     12551
1086     30556
1087     31481
1088     33333
1089     33129
1090     14815
1091     13992
1092     23457
1093     31008
1094     13034
Name: RATE, dtype: object

In [320]:
data1['RATE'] = data1['RATE'].astype('float')

In [321]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   PROPERTY_NAME    1095 non-null   object
 1   SOCIETY          1095 non-null   object
 2   PRICE            958 non-null    float64
 3   RATE             1054 non-null   float64
 4   AREA             1095 non-null   object
 5   AREAWITHTYPE     987 non-null    object
 6   BEDROOM          987 non-null    object
 7   BATHROOM         987 non-null    object
 8   BALCONY          987 non-null    object
 9   ADDITIONALROOM   589 non-null    object
 10  ADDRESS          1031 non-null   object
 11  NOOFFLOOR        967 non-null    object
 12  FACING           674 non-null    object
 13  AGEPOSSESSION    987 non-null    object
 14  NEARBYLOCATIONS  913 non-null    object
 15  DESCRIPTION      1036 non-null   object
 16  FURNISHDETAILS   743 non-null    object
 17  FEATURES         674 non-null    object
 18  RATING           907 non-null    object
dtypes: float64(2), object(17)
memory usage: 162.7+ KB

In [322]:
data1.rename(columns={'RATE':'PRICE_PER_SQFT'},inplace=True)

In [323]:
data1.sample(2)

,PROPERTY_NAME,SOCIETY,PRICE,PRICE_PER_SQFT,AREA,AREAWITHTYPE,BEDROOM,BATHROOM,BALCONY,ADDITIONALROOM,ADDRESS,NOOFFLOOR,FACING,AGEPOSSESSION,NEARBYLOCATIONS,DESCRIPTION,FURNISHDETAILS,FEATURES,RATING
819,12 Bedroom House for sale in Mehrauli Gurgaon ...,nan,8.00,17707.0,(420 sq.m.) Plot Area,Plot area 502(419.74 sq.m.),12 Bedrooms,4 Bathrooms,3+ Balconies,"Servant Room,Store Room","Mehrauli Gurgaon Road, Gurgaon, Haryana",3 Floors,North,10+ Year Old,"['Mg road metro station', 'Iffco chowk metro s...",Its north and park facing. Main iffco chowk wa...,"['1 Wardrobe', '1 Fan', '5 Light', '1 AC', 'No...","['High Ceiling Height', 'Water Storage', 'No o...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
566,2 Bedroom House for sale in Manohar Nagar,nan,0.55,4583.0,(111 sq.m.) Carpet Area,Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,No Balcony,NaN,"Manohar Nagar, Gurgaon, Haryana, India, Manoha...",2 Floors,North-East,undefined,"['Navjeevan Hospital and Maternity Centre', 'S...",65 gaj independent house for sale near sd memo...,NaN,NaN,NaN

In [324]:
data1['BEDROOM'].value_counts()

BEDROOM
4 Bedrooms     240
5 Bedrooms     197
3 Bedrooms     151
2 Bedrooms      91
6 Bedrooms      82
9 Bedrooms      45
1 Bedroom       38
8 Bedrooms      34
7 Bedrooms      32
12 Bedrooms     29
10 Bedrooms     21
16 Bedrooms     12
13 Bedrooms      4
18 Bedrooms      2
19 Bedrooms      2
11 Bedrooms      2
20 Bedrooms      1
21 Bedrooms      1
36 Bedrooms      1
34 Bedrooms      1
14 Bedrooms      1
Name: count, dtype: int64

In [325]:
data1['BEDROOM'].isnull().sum()

108

In [326]:
data1 = data1[~data1['BEDROOM'].isnull()]

In [327]:
data1['BEDROOM'].isnull().sum()

0

In [328]:
data1.shape

(987, 19)

In [329]:
data1['BEDROOM'].value_counts()

BEDROOM
4 Bedrooms     240
5 Bedrooms     197
3 Bedrooms     151
2 Bedrooms      91
6 Bedrooms      82
9 Bedrooms      45
1 Bedroom       38
8 Bedrooms      34
7 Bedrooms      32
12 Bedrooms     29
10 Bedrooms     21
16 Bedrooms     12
13 Bedrooms      4
18 Bedrooms      2
19 Bedrooms      2
11 Bedrooms      2
20 Bedrooms      1
21 Bedrooms      1
36 Bedrooms      1
34 Bedrooms      1
14 Bedrooms      1
Name: count, dtype: int64

In [330]:
data1['BEDROOM'] = data1['BEDROOM'].str.split(" ").str.get(0).str.strip()

<ipython-input-330-d9e2c8175437>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data1['BEDROOM'] = data1['BEDROOM'].str.split(" ").str.get(0).str.strip()

In [331]:
data1.sample(3)

,PROPERTY_NAME,SOCIETY,PRICE,PRICE_PER_SQFT,AREA,AREAWITHTYPE,BEDROOM,BATHROOM,BALCONY,ADDITIONALROOM,ADDRESS,NOOFFLOOR,FACING,AGEPOSSESSION,NEARBYLOCATIONS,DESCRIPTION,FURNISHDETAILS,FEATURES,RATING
404,8 Bedroom House for sale in Laxman Vihar,nan,1.10,6111.0,(167 sq.m.) Plot Area,Plot area 200(167.23 sq.m.),8,4 Bathrooms,3+ Balconies,NaN,"1331/31, Laxman Vihar, Gurgaon, Haryana",2 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...",Location laxman vihar opposite sec-4 near rath...,NaN,['Water Storage'],"['Environment4 out of 5', 'Lifestyle4 out of 5..."
674,8 Bedroom House for sale in DLF Phase 3,dlf city plots phase 3,1.60,29629.0,(50 sq.m.) Plot Area,Plot area 540(50.17 sq.m.)Built Up area: 540 s...,8,5 Bathrooms,3+ Balconies,NaN,"21/24, DLF Phase 3, Gurgaon, Haryana",4 Floors,East,10+ Year Old,"['Dlf phase 3 metro station', 'Micromax moulsa...",Dlf phase 3 u block well located locality,"['9 Fan', '5 Wardrobe', 'No AC', 'No Bed', 'No...",['Park'],"['Environment4 out of 5', 'Lifestyle5 out of 5..."
788,8 Bedroom House for sale in Sector 46 Gurgaon,nan,4.35,23693.0,(171 sq.m.) Plot Area,Plot area 204(170.57 sq.m.),8,8 Bathrooms,2 Balconies,"Study Room,Pooja Room","Sector 46 Gurgaon, Gurgaon, Haryana",3 Floors,North-East,1 to 5 Year Old,"['Axis bank ATM', 'State bank of india ATM', '...",Its a residential building in sector 46. All m...,"['13 Fan', '17 Light', '1 Modular Kitchen', 'N...","['Maintenance Staff', 'False Ceiling Lighting'...","['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [332]:
data1['BATHROOM'].isnull().sum()

0

In [333]:
data1['BATHROOM'].value_counts()

BATHROOM
4 Bathrooms     234
3 Bathrooms     167
5 Bathrooms     139
2 Bathrooms     118
6 Bathrooms      86
1 Bathroom       67
9 Bathrooms      42
7 Bathrooms      39
8 Bathrooms      30
12 Bathrooms     23
10 Bathrooms     11
16 Bathrooms      8
18 Bathrooms      4
13 Bathrooms      4
11 Bathrooms      4
20 Bathrooms      3
17 Bathrooms      3
14 Bathrooms      2
21 Bathrooms      1
36 Bathrooms      1
34 Bathrooms      1
Name: count, dtype: int64

In [334]:
data1['BATHROOM'] = data1['BATHROOM'].str.split(" ").str.get(0).str.strip()

In [335]:
data1.sample(2)

,PROPERTY_NAME,SOCIETY,PRICE,PRICE_PER_SQFT,AREA,AREAWITHTYPE,BEDROOM,BATHROOM,BALCONY,ADDITIONALROOM,ADDRESS,NOOFFLOOR,FACING,AGEPOSSESSION,NEARBYLOCATIONS,DESCRIPTION,FURNISHDETAILS,FEATURES,RATING
742,12 Bedroom House for sale in DLF Phase 2,dlf city plots phase 2,10.0,400000.0,(23 sq.m.) Plot Area,Plot area 250(23.23 sq.m.),12,12,3+ Balconies,"Study Room,Servant Room","Kkmb108, DLF Phase 2, Gurgaon, Haryana",4 Floors,North,1 to 5 Year Old,"['Vodafone belvedere towers metro station', 'D...",12 bedroom with 1 study room.On every floor fl...,"['24 Fan', '1 Exhaust Fan', '12 Geyser', '1 St...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
1077,9 Bedroom House for sale in Sector 40 Gurgaon,nan,5.0,21124.0,(220 sq.m.) Plot Area,Plot area 263(219.9 sq.m.),9,9,3+ Balconies,Pooja Room,"Sector 40 Gurgaon, Gurgaon, Haryana",3 Floors,South-East,1 to 5 Year Old,"['Huda city centre metro station', 'Axis bank ...",263 square yard built up property for sale in ...,"['7 Wardrobe', '15 Fan', '1 Exhaust Fan', '55 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [336]:
data1['BALCONY'].isnull().sum()

0

In [337]:
data1['BALCONY'].value_counts()

BALCONY
3+ Balconies    374
2 Balconies     224
3 Balconies     163
No Balcony      118
1 Balcony       108
Name: count, dtype: int64

In [338]:
data1['BALCONY'] = data1['BALCONY'].str.split(" ").str.get(0).str.replace("No",'0').str.strip()

In [339]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 987 entries, 0 to 1090
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   PROPERTY_NAME    987 non-null    object
 1   SOCIETY          987 non-null    object
 2   PRICE            958 non-null    float64
 3   PRICE_PER_SQFT   958 non-null    float64
 4   AREA             987 non-null    object
 5   AREAWITHTYPE     987 non-null    object
 6   BEDROOM          987 non-null    object
 7   BATHROOM         987 non-null    object
 8   BALCONY          987 non-null    object
 9   ADDITIONALROOM   589 non-null    object
 10  ADDRESS          982 non-null    object
 11  NOOFFLOOR        967 non-null    object
 12  FACING           674 non-null    object
 13  AGEPOSSESSION    987 non-null    object
 14  NEARBYLOCATIONS  864 non-null    object
 15  DESCRIPTION      987 non-null    object
 16  FURNISHDETAILS   743 non-null    object
 17  FEATURES         674 non-null    object
 18  RATING           865 non-null    object
dtypes: float64(2), object(17)
memory usage: 154.2+ KB

In [340]:
data1['BEDROOM'] = data1['BEDROOM'].astype('int')
data1['BATHROOM'] = data1['BATHROOM'].astype('int')

In [341]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 987 entries, 0 to 1090
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   PROPERTY_NAME    987 non-null    object
 1   SOCIETY          987 non-null    object
 2   PRICE            958 non-null    float64
 3   PRICE_PER_SQFT   958 non-null    float64
 4   AREA             987 non-null    object
 5   AREAWITHTYPE     987 non-null    object
 6   BEDROOM          987 non-null    int64
 7   BATHROOM         987 non-null    int64
 8   BALCONY          987 non-null    object
 9   ADDITIONALROOM   589 non-null    object
 10  ADDRESS          982 non-null    object
 11  NOOFFLOOR        967 non-null    object
 12  FACING           674 non-null    object
 13  AGEPOSSESSION    987 non-null    object
 14  NEARBYLOCATIONS  864 non-null    object
 15  DESCRIPTION      987 non-null    object
 16  FURNISHDETAILS   743 non-null    object
 17  FEATURES         674 non-null    object
 18  RATING           865 non-null    object
dtypes: float64(2), int64(2), object(15)
memory usage: 154.2+ KB

In [342]:
data1['ADDITIONALROOM'].isnull().sum()

398

In [343]:
data1['ADDITIONALROOM'].value_counts()

ADDITIONALROOM
Servant Room                                     82
Pooja Room,Study Room,Servant Room,Store Room    63
Others                                           59
Pooja Room                                       38
Pooja Room,Study Room,Servant Room               34
Pooja Room,Study Room,Servant Room,Others        32
Store Room                                       31
Pooja Room,Servant Room                          24
Study Room                                       19
Study Room,Servant Room                          19
Servant Room,Store Room                          15
Pooja Room,Study Room                            11
Pooja Room,Store Room                            11
Pooja Room,Others                                11
Pooja Room,Store Room,Study Room,Servant Room     9
Servant Room,Pooja Room                           8
Servant Room,Others                               8
Pooja Room,Servant Room,Store Room                7
Study Room,Servant Room,Pooja Room,Store Room     7
Servant Room,Pooja Room,Store Room                7
Store Room,Servant Room                           6
Pooja Room,Servant Room,Others                    5
Servant Room,Study Room                           5
Servant Room,Study Room,Pooja Room,Store Room     5
Servant Room,Store Room,Pooja Room                5
Study Room,Pooja Room,Servant Room                5
Study Room,Servant Room,Store Room                4
Pooja Room,Servant Room,Study Room,Store Room     4
Study Room,Servant Room,Store Room,Pooja Room     4
Pooja Room,Study Room,Others                      4
Store Room,Pooja Room                             4
Pooja Room,Study Room,Store Room                  3
Study Room,Servant Room,Pooja Room                3
Study Room,Others                                 3
Study Room,Pooja Room,Servant Room,Store Room     3
Study Room,Pooja Room,Store Room,Servant Room     2
Pooja Room,Study Room,Store Room,Servant Room     2
Study Room,Servant Room,Others                    2
Store Room,Pooja Room,Study Room,Servant Room     2
Study Room,Pooja Room                             2
Store Room,Pooja Room,Study Room                  2
Store Room,Pooja Room,Servant Room                2
Servant Room,Study Room,Pooja Room                2
Servant Room,Study Room,Store Room,Pooja Room     2
Study Room,Pooja Room,Store Room                  2
Study Room,Store Room                             1
Study Room,Store Room,Pooja Room                  1
Store Room,Pooja Room,Servant Room,Study Room     1
Servant Room,Store Room,Study Room,Pooja Room     1
Store Room,Servant Room,Study Room,Pooja Room     1
Pooja Room,Store Room,Servant Room                1
Servant Room,Others,Pooja Room                    1
Study Room,Store Room,Servant Room,Pooja Room     1
Store Room,Study Room,Servant Room                1
Store Room,Servant Room,Pooja Room                1
Study Room,Others,Servant Room                    1
Name: count, dtype: int64

In [344]:
data1.head()

,PROPERTY_NAME,SOCIETY,PRICE,PRICE_PER_SQFT,AREA,AREAWITHTYPE,BEDROOM,BATHROOM,BALCONY,ADDITIONALROOM,ADDRESS,NOOFFLOOR,FACING,AGEPOSSESSION,NEARBYLOCATIONS,DESCRIPTION,FURNISHDETAILS,FEATURES,RATING
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3+,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,nan,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,nan,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3+,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,nan,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3+,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,nan,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3+,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [345]:
data1['ADDITIONALROOM'].fillna("not available",inplace=True)

In [346]:
data1['ADDITIONALROOM'].value_counts()

ADDITIONALROOM
not available                                    398
Servant Room                                      82
Pooja Room,Study Room,Servant Room,Store Room     63
Others                                            59
Pooja Room                                        38
Pooja Room,Study Room,Servant Room                34
Pooja Room,Study Room,Servant Room,Others         32
Store Room                                        31
Pooja Room,Servant Room                           24
Study Room,Servant Room                           19
Study Room                                        19
Servant Room,Store Room                           15
Pooja Room,Store Room                             11
Pooja Room,Study Room                             11
Pooja Room,Others                                 11
Pooja Room,Store Room,Study Room,Servant Room      9
Servant Room,Pooja Room                            8
Servant Room,Others                                8
Study Room,Servant Room,Pooja Room,Store Room      7
Pooja Room,Servant Room,Store Room                 7
Servant Room,Pooja Room,Store Room                 7
Store Room,Servant Room                            6
Pooja Room,Servant Room,Others                     5
Study Room,Pooja Room,Servant Room                 5
Servant Room,Store Room,Pooja Room                 5
Servant Room,Study Room,Pooja Room,Store Room      5
Servant Room,Study Room                            5
Store Room,Pooja Room                              4
Study Room,Servant Room,Store Room                 4
Pooja Room,Servant Room,Study Room,Store Room      4
Study Room,Servant Room,Store Room,Pooja Room      4
Pooja Room,Study Room,Others                       4
Study Room,Others                                  3
Study Room,Pooja Room,Servant Room,Store Room      3
Study Room,Servant Room,Pooja Room                 3
Pooja Room,Study Room,Store Room                   3
Study Room,Servant Room,Others                     2
Study Room,Pooja Room,Store Room,Servant Room      2
Study Room,Pooja Room                              2
Store Room,Pooja Room,Servant Room                 2
Study Room,Pooja Room,Store Room                   2
Pooja Room,Study Room,Store Room,Servant Room      2
Store Room,Pooja Room,Study Room                   2
Store Room,Pooja Room,Study Room,Servant Room      2
Servant Room,Study Room,Store Room,Pooja Room      2
Servant Room,Study Room,Pooja Room                 2
Study Room,Store Room                              1
Store Room,Pooja Room,Servant Room,Study Room      1
Servant Room,Store Room,Study Room,Pooja Room      1
Study Room,Store Room,Pooja Room                   1
Store Room,Servant Room,Study Room,Pooja Room      1
Pooja Room,Store Room,Servant Room                 1
Servant Room,Others,Pooja Room                     1
Study Room,Store Room,Servant Room,Pooja Room      1
Store Room,Study Room,Servant Room                 1
Store Room,Servant Room,Pooja Room                 1
Study Room,Others,Servant Room                     1
Name: count, dtype: int64

In [347]:
data1['ADDITIONALROOM']

0                                        Servant Room
1                  Store Room,Pooja Room,Servant Room
2                                        Servant Room
3                                        Servant Room
4                                              Others
5                                        Servant Room
6                  Servant Room,Pooja Room,Store Room
7                                        Servant Room
8                                          Store Room
9                                        Servant Room
10                                         Store Room
11      Study Room,Servant Room,Pooja Room,Store Room
12                                         Pooja Room
13      Pooja Room,Study Room,Servant Room,Store Room
14      Study Room,Servant Room,Store Room,Pooja Room
15                              Pooja Room,Study Room
16                 Servant Room,Pooja Room,Store Room
17                   Store Room,Pooja Room,Study Room
18                            Pooja Room,Servant Room
19      Pooja Room,Study Room,Servant Room,Store Room
20                                      not available
21                            Store Room,Servant Room
22                            Pooja Room,Servant Room
23                 Pooja Room,Servant Room,Store Room
24                   Study Room,Pooja Room,Store Room
25                 Pooja Room,Study Room,Servant Room
26                 Pooja Room,Study Room,Servant Room
27                                         Study Room
28                            Servant Room,Store Room
29                                       Servant Room
30                   Pooja Room,Study Room,Store Room
31                            Store Room,Servant Room
32                                         Pooja Room
33                                       Servant Room
34                                      not available
35                                         Store Room
36      Pooja Room,Study Room,Servant Room,Store Room
37                                         Store Room
38                                         Study Room
39      Pooja Room,Study Room,Servant Room,Store Room
40      Pooja Room,Study Room,Servant Room,Store Room
41                                         Store Room
42                 Study Room,Pooja Room,Servant Room
43          Pooja Room,Study Room,Servant Room,Others
44                                       Servant Room
45                            Pooja Room,Servant Room
46                            Pooja Room,Servant Room
47                 Pooja Room,Study Room,Servant Room
48      Pooja Room,Store Room,Study Room,Servant Room
49                 Servant Room,Pooja Room,Store Room
50                                      not available
51      Pooja Room,Study Room,Servant Room,Store Room
52      Pooja Room,Study Room,Servant Room,Store Room
53                 Servant Room,Store Room,Pooja Room
54                                             Others
55      Servant Room,Study Room,Store Room,Pooja Room
56                 Pooja Room,Study Room,Servant Room
57                                      not available
58      Pooja Room,Study Room,Servant Room,Store Room
59      Study Room,Servant Room,Pooja Room,Store Room
73                                       Servant Room
74                                             Others
77                                      not available
78                            Pooja Room,Servant Room
92                                         Store Room
93                                      not available
103                                      Servant Room
104                               Servant Room,Others
114                Servant Room,Pooja Room,Store Room
119                                     not available
120                                     not available
121                Servant Room,Study Room,Pooja Room
122     Pooja Room,Study Room,Servant Room,Store Room
125                           Pooja Room,Servant Room
126                                 Pooja Room,Others
127                                      Servant Room
129     Study Room,Pooja Room,Servant Room,Store Room
130                                     not available
131                Study Room,Pooja Room,Servant Room
132     Pooja Room,Study Room,Servant Room,Store Room
133                Pooja Room,Study Room,Servant Room
134                                     not available
135                                     not available
136                                     not available
137                                     not available
138                                     not available
139                                      Servant Room
140         Pooja Room,Study Room,Servant Room,Others
141                           Study Room,Servant Room
142     Pooja Room,Study Room,Servant Room,Store Room
143                                      Servant Room
144                Pooja Room,Study Room,Servant Room
145                                      Servant Room
146                                      Servant Room
147                                            Others
148                                        Store Room
149                                      Servant Room
150                                      Servant Room
151                                      Servant Room
152     Pooja Room,Store Room,Study Room,Servant Room
153                           Study Room,Servant Room
154                                     not available
155                           Study Room,Servant Room
156                                 Pooja Room,Others
157                                            Others
158                                            Others
159                                 Pooja Room,Others
160                                            Others
161                                            Others
162                                            Others
163                               Servant Room,Others
164                                      Servant Room
165                                      Servant Room
166                                            Others
167                                     not available
168                Study Room,Servant Room,Pooja Room
169                                            Others
170                                            Others
171                                      Servant Room
172                                      Servant Room
173                                        Pooja Room
174         Pooja Room,Study Room,Servant Room,Others
175                Pooja Room,Study Room,Servant Room
176     Pooja Room,Store Room,Study Room,Servant Room
177                           Study Room,Servant Room
200                             Pooja Room,Store Room
201                                            Others
202                                        Study Room
203                                     not available
204                                     not available
205                      Pooja Room,Study Room,Others
206                                     not available
207                                     not available
208                                            Others
209                                        Study Room
210     Pooja Room,Study Room,Servant Room,Store Room
211     Study Room,Servant Room,Store Room,Pooja Room
212                                     not available
213                                     not available
214                               Servant Room,Others
215                                            Others
216                                        Pooja Room
217                                        Pooja Room
218                                     not available
219                                     not available
220                                     not available
221                                     not available
222                                     not available
223                                     not available
224                                     not available
225                             Pooja Room,Study Room
226                                     not available
227                Study Room,Servant Room,Pooja Room
228                                     not available
229                                     not available
230                                     not available
231                                     not available
232                                     not available
233                                     not available
234                                     not available
235                                     not available
236                                     not available
237                                     not available
238                                     not available
239         Pooja Room,Study Room,Servant Room,Others
240                             Pooja Room,Study Room
241                                     not available
242                                     not available
243                                     not available
244                                     not available
245                                     not available
246                                     not available
247                                     not available
248                                        Pooja Room
249                                     not available
250     Pooja Room,Study Room,Servant Room,Store Room
251                                     not available
252                                     not available
253                                     not available
254                                     not available
255                                     not available
256                                     not available
257                                        Pooja Room
258                                        Store Room
259                                     not available
260                           Pooja Room,Servant Room
261                                     not available
262                                     not available
263         Pooja Room,Study Room,Servant Room,Others
264                                      Servant Room
265                                     not available
266                                     not available
267                                     not available
268                                     not available
269                                     not available
270                                     not available
271                                     not available
272                                     not available
273                                     not available
274                                     not available
275                                     not available
276                                     not available
277                                        Pooja Room
278                                            Others
279                                     not available
280                                     not available
281                                     not available
282                                      Servant Room
283                                     not available
284                                     not available
285                                     not available
286                                     not available
287                               Servant Room,Others
288                                            Others
289                                     not available
290                                     not available
291                                     not available
292                                            Others
293                                     not available
294                                     not available
295                                     not available
296                                     not available
297                                     not available
298                                     not available
299                                     not available
300                                     not available
301                                     not available
302                                     not available
303                                     not available
304                                     not available
305                                     not available
306                                     not available
307                                     not available
309                                        Pooja Room
310                                     not available
311                                     not available
314                                     not available
315                                            Others
316                                     not available
317                                     not available
318                                     not available
320                                      Servant Room
321                                        Pooja Room
322                                     not available
323                                     not available
324                                     not available
325                                     not available
326                                     not available
332                                     not available
333                                     not available
334                                     not available
335                                     not available
336                                     not available
337                                     not available
338                                            Others
339                Pooja Room,Study Room,Servant Room
340                                     not available
341                                            Others
342                                            Others
343                                     not available
344                                     not available
345                                     not available
346                                     not available
347                                     not available
348                                     not available
349                                     not available
350                                     not available
351                                     not available
352                                     not available
357                                     not available
370                                     not available
374                                     not available
375                                     not available
376                                     not available
377                                     not available
378                                     not available
379                                     not available
380                                     not available
381                                     not available
382                             Pooja Room,Study Room
383                                     not available
384                                        Pooja Room
385                                     not available
386                                     not available
387                                        Pooja Room
388                                     not available
389                                     not available
390                                     not available
391                                     not available
392                                     not available
393                                     not available
394                                     not available
395                                     not available
396                                        Pooja Room
397                                     not available
398                                            Others
399                                     not available
400                Pooja Room,Study Room,Servant Room
401                                     not available
402                                     not available
403                                     not available
404                                     not available
405                                     not available
406                                     not available
407                                     not available
408                                     not available
409                                     not available
410         Pooja Room,Study Room,Servant Room,Others
411                                     not available
412                                     not available
413                                            Others
414                                     not available
415                                     not available
416                                     not available
417                                            Others
418                                     not available
419                                     not available
420                    Pooja Room,Servant Room,Others
421                             Pooja Room,Study Room
422                                     not available
423                                     not available
424                                     not available
425                                     not available
426                                     not available
427                                     not available
428                             Pooja Room,Store Room
429                                            Others
430                                        Store Room
431                                     not available
432                           Servant Room,Store Room
433                                     not available
434                           Servant Room,Study Room
435                                     not available
436                                     not available
437                                            Others
438                                     not available
439                                            Others
440                                     not available
441                                            Others
442                                      Servant Room
443                                     not available
444                                     not available
445                                            Others
446                                 Study Room,Others
447                                     not available
448                                     not available
449         Pooja Room,Study Room,Servant Room,Others
450                                     not available
451                                     not available
452                      Pooja Room,Study Room,Others
453                                     not available
454                                     not available
455                                     not available
456                                     not available
457                                     not available
458                                     not available
459                                      Servant Room
460                                     not available
461                                     not available
462                                     not available
463                                     not available
464                                 Pooja Room,Others
465                                            Others
466                                     not available
467         Pooja Room,Study Room,Servant Room,Others
468                                     not available
469                                     not available
470                                     not available
471                                            Others
472                                     not available

In [348]:
data1['ADDITIONALROOM'] = data1['ADDITIONALROOM'].str.lower()

In [349]:
data1.sample(5)

,PROPERTY_NAME,SOCIETY,PRICE,PRICE_PER_SQFT,AREA,AREAWITHTYPE,BEDROOM,BATHROOM,BALCONY,ADDITIONALROOM,ADDRESS,NOOFFLOOR,FACING,AGEPOSSESSION,NEARBYLOCATIONS,DESCRIPTION,FURNISHDETAILS,FEATURES,RATING
758,12 Bedroom House for sale in Sector 46 Gurgaon,nan,6.5,27461.0,(220 sq.m.) Plot Area,Plot area 263(219.9 sq.m.),12,12,3+,"pooja room,study room","Sector 46 Gurgaon, Gurgaon, Haryana",4 Floors,North-West,1 to 5 Year Old,"['Axis bank ATM', 'State bank of india ATM', '...",This 12 bhk house for sale in sector 46 gurgao...,"['1 Water Purifier', '1 Fridge', '10 Fan', '1 ...","['Feng Shui / Vaastu Compliant', 'Maintenance ...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
350,6 Bedroom House for sale in Ashok Vihar Phase ...,nan,1.5,5000.0,(279 sq.m.) Built-up Area,Built Up area: 3000 (278.71 sq.m.),6,1,0,not available,"Ashok Vihar Phase 3 Extension, Ashok Vihar Pha...",1 Floors,NaN,0 to 1 Year Old,NaN,Best in class property available at ashok viha...,NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
370,34 Bedroom House for sale in Manohar Nagar,manohar nagar,5.6,12444.0,(418 sq.m.) Plot Area,Plot area 500(418.06 sq.m.)Built Up area: 500 ...,34,34,3+,not available,"230/26, Manohar Nagar, Gurgaon, Haryana",4 Floors,NaN,0 to 1 Year Old,"['Shiv Mahima Patient Care Bureau', 'Navjeevan...",This is a newly constructed building. With pro...,"['36 Fan', '51 Light', 'No AC', 'No Bed', 'No ...",NaN,NaN
294,1 Bedroom House for sale in Mianwali Colony,project mianwali colony,1.7,9444.0,(167 sq.m.) Carpet Area,Carpet area: 1800 (167.23 sq.m.),1,1,2,not available,"Mianwali Colony, Sector 12a, Mianwali Colony, ...",1 Floors,NaN,undefined,"['Hanuman Mandir', 'Sheetla Mata Mandir', 'Lal...",Best in class property available at mianwali c...,NaN,NaN,"['Environment3.5 out of 5', 'Lifestyle4 out of..."
614,10 Bedroom House for sale in Rajiv Chowk,hans enclave,2.0,10582.0,(176 sq.m.) Built-up Area,Built Up area: 210 (175.59 sq.m.),10,10,3,not available,"Rajiv Chowk, Gurgaon, Haryana",3 Floors,NaN,5 to 10 Year Old,"['Rajiv Chowk Mosque', 'Hanuman Mandir', 'Hdfc...",I have a house/villa available for sale in raj...,NaN,NaN,"['Environment3.5 out of 5', 'Lifestyle4 out of..."

In [350]:
data1['NOOFFLOOR'].isnull().sum()

20

In [351]:
data1['NOOFFLOOR'].value_counts()

NOOFFLOOR
3 Floors     309
2 Floors     300
1 Floors     183
4 Floors     139
5 Floors       9
0 Floors       6
14 Floors      3
6 Floors       3
11 Floors      2
12 Floors      2
10 Floors      2
16 Floors      1
51 Floors      1
41 Floors      1
27 Floors      1
20 Floors      1
13 Floors      1
21 Floors      1
02 Floors      1
33 Floors      1
Name: count, dtype: int64

In [352]:
data1['NOOFFLOOR']

0        3 Floors
1        2 Floors
2        5 Floors
3        5 Floors
4        5 Floors
5        4 Floors
6        3 Floors
7        4 Floors
8        3 Floors
9        4 Floors
10       2 Floors
11       3 Floors
12       4 Floors
13       3 Floors
14       3 Floors
15       3 Floors
16       3 Floors
17       3 Floors
18       3 Floors
19       3 Floors
20       3 Floors
21       3 Floors
22       2 Floors
23            NaN
24       4 Floors
25       3 Floors
26       1 Floors
27       3 Floors
28       3 Floors
29       3 Floors
30       2 Floors
31       3 Floors
32       3 Floors
33       1 Floors
34       2 Floors
35       3 Floors
36       4 Floors
37       1 Floors
38       3 Floors
39       3 Floors
40       2 Floors
41       1 Floors
42       4 Floors
43       4 Floors
44       4 Floors
45       4 Floors
46       2 Floors
47       3 Floors
48       3 Floors
49       2 Floors
50       2 Floors
51            NaN
52       3 Floors
53       2 Floors
54       3 Floors
55       2 Floors
56       2 Floors
57       2 Floors
58       3 Floors
59       3 Floors
73       3 Floors
74       3 Floors
77       1 Floors
78       3 Floors
92       4 Floors
93       2 Floors
103      2 Floors
104      2 Floors
114      3 Floors
119      2 Floors
120      1 Floors
121      3 Floors
122      2 Floors
125      2 Floors
126      1 Floors
127      3 Floors
129      3 Floors
130      1 Floors
131      4 Floors
132      2 Floors
133      1 Floors
134      1 Floors
135      3 Floors
136      2 Floors
137      2 Floors
138      2 Floors
139      3 Floors
140      2 Floors
141      3 Floors
142      3 Floors
143      2 Floors
144      3 Floors
145      2 Floors
146      2 Floors
147      3 Floors
148      2 Floors
149      2 Floors
150      2 Floors
151      2 Floors
152      3 Floors
153      2 Floors
154      2 Floors
155      2 Floors
156      1 Floors
157      2 Floors
158      1 Floors
159      2 Floors
160      1 Floors
161      2 Floors
162      2 Floors
163      2 Floors
164      2 Floors
165      3 Floors
166      4 Floors
167      4 Floors
168      2 Floors
169      4 Floors
170      1 Floors
171      2 Floors
172      2 Floors
173      2 Floors
174      4 Floors
175      4 Floors
176      3 Floors
177      4 Floors
200      3 Floors
201      3 Floors
202      2 Floors
203           NaN
204      1 Floors
205      3 Floors
206      1 Floors
207      1 Floors
208      4 Floors
209      2 Floors
210      3 Floors
211      4 Floors
212      2 Floors
213      1 Floors
214      3 Floors
215      3 Floors
216      3 Floors
217      2 Floors
218      1 Floors
219      3 Floors
220     02 Floors
221      3 Floors
222      2 Floors
223      2 Floors
224      2 Floors
225      1 Floors
226      1 Floors
227      1 Floors
228      2 Floors
229      2 Floors
230      2 Floors
231      1 Floors
232      1 Floors
233      1 Floors
234      3 Floors
235      1 Floors
236      1 Floors
237      3 Floors
238      3 Floors
239      1 Floors
240      3 Floors
241     14 Floors
242     21 Floors
243      1 Floors
244      1 Floors
245      2 Floors
246      3 Floors
247      1 Floors
248      1 Floors
249      1 Floors
250      2 Floors
251      0 Floors
252           NaN
253      3 Floors
254      3 Floors
255      3 Floors
256      1 Floors
257      2 Floors
258      3 Floors
259      3 Floors
260      2 Floors
261      1 Floors
262      3 Floors
263      2 Floors
264      3 Floors
265      1 Floors
266      1 Floors
267      1 Floors
268      3 Floors
269      3 Floors
270           NaN
271      3 Floors
272      1 Floors
273      3 Floors
274     12 Floors
275      1 Floors
276      2 Floors
277      2 Floors
278      2 Floors
279      1 Floors
280      3 Floors
281           NaN
282      3 Floors
283      1 Floors
284      3 Floors
285      2 Floors
286      3 Floors
287      2 Floors
288      0 Floors
289      1 Floors
290      1 Floors
291      1 Floors
292      0 Floors
293      3 Floors
294      1 Floors
295      1 Floors
296      2 Floors
297      2 Floors
298      2 Floors
299      1 Floors
300      1 Floors
301      1 Floors
302      2 Floors
303     27 Floors
304      4 Floors
305      3 Floors
306      3 Floors
307      2 Floors
309      1 Floors
310      1 Floors
311      1 Floors
314      1 Floors
315      3 Floors
316      3 Floors
317      4 Floors
318      4 Floors
320      4 Floors
321      1 Floors
322      3 Floors
323      2 Floors
324      3 Floors
325      2 Floors
326      2 Floors
332      4 Floors
333      2 Floors
334      1 Floors
335      2 Floors
336      1 Floors
337      2 Floors
338      2 Floors
339      4 Floors
340      1 Floors
341      1 Floors
342      2 Floors
343      3 Floors
344      1 Floors
345      2 Floors
346      3 Floors
347     13 Floors
348      1 Floors
349      1 Floors
350      1 Floors
351      1 Floors
352      3 Floors
357      2 Floors
370      4 Floors
374           NaN
375      3 Floors
376      3 Floors
377      3 Floors
378      6 Floors
379      2 Floors
380      4 Floors
381      1 Floors
382      3 Floors
383      1 Floors
384      1 Floors
385      1 Floors
386      1 Floors
387      2 Floors
388      1 Floors
389      3 Floors
390      1 Floors
391      3 Floors
392      1 Floors
393      4 Floors
394      3 Floors
395      1 Floors
396      3 Floors
397           NaN
398      2 Floors
399      2 Floors
400      3 Floors
401      1 Floors
402      4 Floors
403      2 Floors
404      2 Floors
405      1 Floors
406      1 Floors
407      1 Floors
408      1 Floors
409      1 Floors
410      3 Floors
411      3 Floors
412      1 Floors
413      3 Floors
414      4 Floors
415      4 Floors
416      2 Floors
417           NaN
418      1 Floors
419      1 Floors
420      3 Floors
421      2 Floors
422      4 Floors
423      2 Floors
424      2 Floors
425      1 Floors
426      1 Floors
427      1 Floors
428      3 Floors
429      3 Floors
430      1 Floors
431      4 Floors
432      4 Floors
433      1 Floors
434      4 Floors
435      2 Floors
436      2 Floors
437      3 Floors
438      6 Floors
439      2 Floors
440      2 Floors
441      3 Floors
442      2 Floors
443      3 Floors
444      3 Floors
445      4 Floors
446      1 Floors
447      1 Floors
448      1 Floors
449      3 Floors
450      2 Floors
451      2 Floors
452      1 Floors
453      1 Floors
454      1 Floors
455      1 Floors
456      1 Floors
457      2 Floors
458      1 Floors
459      1 Floors
460      3 Floors
461      2 Floors
462      2 Floors
463      1 Floors
464      3 Floors
465      3 Floors
466      2 Floors
467      3 Floors
468      1 Floors
469      1 Floors
470      1 Floors
471      2 Floors
472      3 Floors
473      2 Floors
474      4 Floors
475      3 Floors
476      3 Floors
477      1 Floors
478     10 Floors
479      4 Floors
480      4 Floors
481      1 Floors
482      2 Floors
483      3 Floors
484      2 Floors
485      1 Floors
486      2 Floors
487      1 Floors
488      2 Floors
489      5 Floors
490      1 Floors
491      4 Floors
492      3 Floors
493      2 Floors
494      2 Floors
495      1 Floors
496      1 Floors
497      3 Floors
498      3 Floors
499      2 Floors
500      1 Floors
501     20 Floors
502      3 Floors
503      3 Floors
504      4 Floors
505      3 Floors
506      3 Floors
507      3 Floors
508      2 Floors
509      2 Floors
510      1 Floors
511      2 Floors
512      3 Floors
513      3 Floors
514      2 Floors
515      2 Floors
516      4 Floors
517      2 Floors
518      3 Floors
519      3 Floors
520      1 Floors
521      4 Floors
522      1 Floors
523      1 Floors
524      2 Floors
525      3 Floors
526      1 Floors
527      1 Floors
528      1 Floors
529      1 Floors
530      1 Floors
531      2 Floors
532      1 Floors
533      3 Floors
534      1 Floors
535      3 Floors
536      3 Floors
537      1 Floors
538      1 Floors
539      2 Floors
540      4 Floors
541      1 Floors
542      1 Floors
543      1 Floors
544      4 Floors
545      2 Floors
546      3 Floors
547      4 Floors
548      2 Floors
549      2 Floors
550      1 Floors
551      2 Floors
552      1 Floors
553      1 Floors
554      3 Floors
555      4 Floors
556      3 Floors
557      4 Floors
558      1 Floors
559      4 Floors
560           NaN
561      2 Floors
562      2 Floors
563      0 Floors
564      2 Floors
565      3 Floors
566      2 Floors
567      3 Floors
568      3 Floors
569      2 Floors
570      3 Floors
571      3 Floors
572      1 Floors
573      1 Floors
574      3 Floors
575     14 Floors
576      1 Floors
577      3 Floors
578      3 Floors
579      3 Floors
580      4 Floors
581     14 Floors
582     12 Floors
583      1 Floors
584      4 Floors
585      3 Floors
586      4 Floors
587      1 Floors
588      2 Floors
589      3 Floors
590      1 Floors
591      1 Floors
592      2 Floors
593      4 Floors
594           NaN
595      1 Floors
596      2 Floors
597      3 Floors
598      2 Floors
599      3 Floors
600      2 Floors
601      1 Floors
602      1 Floors
603      1 Floors
604      1 Floors
605      3 Floors
606      1 Floors
607      1 Floors
608      3 Floors
609      1 Floors
610      2 Floors
611      1 Floors
612      2 Floors
613      3 Floors
614      3 Floors
615      3 Floors
616      3 Floors
617      1 Floors
618      1 Floors
619      2 Floors
620      1 Floors
621      3 Floors
622     11 Floors
623      0 Floors
624      3 Floors
625      4 Floors
626      3 Floors
627      3 Floors
628      3 Floors
629      4 Floors
630      1 Floors
631      4 Floors
632      3 Floors
633      1 Floors
634      1 Floors
635      5 Floors
636      4 Floors
637     11 Floors
638      1 Floors
639      2 Floors
640      1 Floors
641     41 Floors
642      1 Floors
643      1 Floors
644      3 Floors
645      1 Floors
646      3 Floors
647      4 Floors
648      1 Floors
649      5 Floors
650      2 Floors
651      2 Floors
652      3 Floors
653      3 Floors
654      2 Floors
655      2 Floors
656      4 Floors
657      3 Floors
658      5 Floors
659      3 Floors
660      1 Floors
661      1 Floors
662      3 Floors
663      2 Floors
664      3 Floors
665      1 Floors
666           NaN
667      3 Floors
668      2 Floors
669      1 Floors
670      2 Floors
671      3 Floors
672      4 Floors
673      4 Floors
674      4 Floors
675      2 Floors
676      2 Floors
677      3 Floors
678      1 Floors
679      2 Floors
680      2 Floors
681      2 Floors
682      2 Floors
683      1 Floors
684      3 Floors
685      4 Floors
686      2 Floors
687      1 Floors
688      2 Floors
689      1 Floors
690      1 Floors
691      3 Floors
692      4 Floors
693      3 Floors
694      4 Floors
695      4 Floors
696      3 Floors
697      3 Floors
698      3 Floors
699      3 Floors
700      3 Floors
701      3 Floors
702      1 Floors
703      3 Floors
704      3 Floors
705      2 Floors
706      3 Floors
707      3 Floors
708      4 Floors
709           NaN
710      3 Floors
711      2 Floors
712      2 Floors
713      4 Floors
714      1 Floors
715      3 Floors
716      4 Floors
717      2 Floors
718      3 Floors
719      3 Floors
720      3 Floors
721      2 Floors
722      3 Floors
723      2 Floors
724      2 Floors
725      4 Floors
726     10 Floors
727      3 Floors
728      4 Floors
729      2 Floors
730      4 Floors
731      2 Floors
732      3 Floors
733      3 Floors
734      3 Floors
735      2 Floors
736      1 Floors
737      4 Floors
738      2 Floors
739      4 Floors
740      2 Floors
741      3 Floors
742      4 Floors
743      2 Floors
744      2 Floors
745      2 Floors
746      3 Floors
747      4 Floors
748      5 Floors
749      4 Floors
750      4 Floors
751      3 Floors
752      3 Floors
753      3 Floors
754      4 Floors
755      2 Floors
756      2 Floors
757      2 Floors
758      4 Floors
759      4 Floors
760     51 Floors
761      3 Floors
762      3 Floors
763      2 Floors
764      3 Floors
765      2 Floors
766      2 Floors
767      2 Floors
768      3 Floors
769      1 Floors
770      3 Floors
771      2 Floors
772      2 Floors
773      4 Floors
774      3 Floors
775      4 Floors
776      3 Floors
777      2 Floors
778      4 Floors
779      2 Floors
780      3 Floors
781      1 Floors
782      2 Floors
783      1 Floors
784      3 Floors
785      3 Floors
786      4 Floors
787      3 Floors
788      3 Floors
789      2 Floors
790      3 Floors
791      2 Floors
792      4 Floors
793      2 Floors
794      2 Floors
795      3 Floors
796      4 Floors
797      2 Floors
798      2 Floors
799      4 Floors
800      3 Floors
801      2 Floors
802      3 Floors
803      2 Floors
804      2 Floors
805      4 Floors
806      2 Floors
807      3 Floors
808      3 Floors
809      2 Floors
810      2 Floors
811      2 Floors
812      2 Floors
813      3 Floors
814      4 Floors
815      2 Floors
816      2 Floors
817      2 Floors
818      4 Floors
819      3 Floors
820      3 Floors
821      2 Floors
822      2 Floors
823           NaN
824      3 Floors
825      2 Floors
826      3 Floors
827      2 Floors
828      2 Floors
829      2 Floors
830      3 Floors
831      3 Floors
832           NaN
833      4 Floors
834      4 Floors
835      3 Floors
836      3 Floors
837      4 Floors
838      3 Floors
839      3 Floors
840      2 Floors
841      4 Floors
842      3 Floors
843      3 Floors
844      4 Floors
845      4 Floors
846      3 Floors
847      4 Floors
848      4 Floors
849      3 Floors
850      4 Floors
851      1 Floors
852      3 Floors
853      2 Floors
854      4 Floors
855           NaN
856      2 Floors
857      2 Floors
858      2 Floors
859      4 Floors
860      3 Floors
861      4 Floors
862           NaN
863      3 Floors
864      4 Floors
865           NaN
866      2 Floors
867      2 Floors
868      2 Floors
869      3 Floors
870      2 Floors
871      4 Floors
872      3 Floors
873      4 Floors
874      4 Floors
875      3 Floors
876      3 Floors
877      3 Floors
878      3 Floors
879      2 Floors
880      2 Floors
881      2 Floors
882      2 Floors
883     16 Floors
884      4 Floors
885      2 Floors
886      3 Floors
887      1 Floors
888      2 Floors
889      2 Floors
890      3 Floors
891      3 Floors
892      3 Floors
893      1 Floors
895      1 Floors
896      1 Floors
897      2 Floors
898      3 Floors
899      3 Floors
900      4 Floors
901      3 Floors
902      2 Floors
903      4 Floors
904      2 Floors
905      3 Floors
906      2 Floors
907      2 Floors
908      4 Floors
909      4 Floors
910      2 Floors
911      3 Floors
912      2 Floors
913      4 Floors
914      4 Floors
915      4 Floors
916      4 Floors
917      2 Floors
918      2 Floors
919      2 Floors
920      2 Floors
921      3 Floors
922      2 Floors
923      3 Floors
924      2 Floors
925      2 Floors
926      3 Floors
927      3 Floors
928      4 Floors
929      4 Floors
930      2 Floors
931      3 Floors
932      2 Floors
933      3 Floors
934      4 Floors
935      3 Floors
936      3 Floors
937      1 Floors
938      2 Floors
939      3 Floors
940      3 Floors
941      2 Floors
942      3 Floors
943      2 Floors
944      3 Floors
945      4 Floors
946      2 Floors
947      3 Floors
948      4 Floors
949      3 Floors
950      3 Floors
951      3 Floors
952      4 Floors
953      3 Floors
954      2 Floors
955      2 Floors
956      2 Floors
957      3 Floors
958      3 Floors
959      3 Floors
960      1 Floors
961      3 Floors
962      2 Floors
963      4 Floors
964      4 Floors
965      3 Floors
966      3 Floors
967      2 Floors
968      4 Floors
969      3 Floors
970      2 Floors
971      2 Floors
972      3 Floors
973      2 Floors
974      2 Floors
975      2 Floors
976      2 Floors
977      2 Floors
978      2 Floors
979      3 Floors
980      6 Floors
981      1 Floors
982      2 Floors
983      2 Floors
984      4 Floors
985      3 Floors
986      3 Floors
987      2 Floors
988      2 Floors
989      4 Floors
990      3 Floors
991      2 Floors
992      2 Floors
993      2 Floors
994      2 Floors
995      2 Floors
996      3 Floors
997      4 Floors
998      4 Floors
999      3 Floors
1000     3 Floors
1001     3 Floors
1002     2 Floors
1003          NaN
1004     4 Floors
1005     3 Floors
1006     2 Floors
1007     2 Floors
1008     2 Floors
1009     2 Floors
1010     2 Floors
1011     2 Floors
1012     2 Floors
1013     2 Floors
1014     2 Floors
1015     3 Floors
1016          NaN
1017     3 Floors
1018     2 Floors
1019     1 Floors
1020     3 Floors
1021     2 Floors
1022     3 Floors
1023     1 Floors
1024     2 Floors
1025     2 Floors
1026     2 Floors
1027     2 Floors
1028     3 Floors
1029     2 Floors
1030     3 Floors
1031     3 Floors
1032     2 Floors
1033     3 Floors
1034    33 Floors
1035     3 Floors
1036     2 Floors
1037     3 Floors
1038     3 Floors
1039     2 Floors
1040     3 Floors
1041     2 Floors
1042     2 Floors
1043     2 Floors
1044     2 Floors
1045     2 Floors
1046     1 Floors
1047     3 Floors
1048     3 Floors
1049     3 Floors
1050     4 Floors
1051     4 Floors
1052     0 Floors
1053     4 Floors
1054     4 Floors
1055     2 Floors
1056     2 Floors
1057     3 Floors
1058     3 Floors
1059     2 Floors
1060     4 Floors
1061     4 Floors
1062     3 Floors
1063     3 Floors
1064     3 Floors
1065     2 Floors
1066     4 Floors
1067     3 Floors
1068     4 Floors
1069     5 Floors
1070     3 Floors
1071     2 Floors
1072     3 Floors
1073     2 Floors
1074     3 Floors
1075     2 Floors
1076     3 Floors
1077     3 Floors
1078     3 Floors
1079     2 Floors
1080     3 Floors
1081     3 Floors
1082     3 Floors
1083     2 Floors
1084     2 Floors
1085     2 Floors
1086     2 Floors
1087     2 Floors
1088     2 Floors
1089     2 Floors
1090     2 Floors
Name: NOOFFLOOR, dtype: object

In [353]:
data1['NOOFFLOOR'] = data1['NOOFFLOOR'].str.split(" ").str.get(0).str.strip()

In [354]:
data1['NOOFFLOOR'].fillna(0,inplace=True)

In [355]:
data1['NOOFFLOOR'] = data1['NOOFFLOOR'].astype('int32')

In [356]:
data1.rename(columns={"NOOFFLOOR":'FLOORNUM'},inplace=True)

In [357]:
data1.sample(3)

,PROPERTY_NAME,SOCIETY,PRICE,PRICE_PER_SQFT,AREA,AREAWITHTYPE,BEDROOM,BATHROOM,BALCONY,ADDITIONALROOM,ADDRESS,FLOORNUM,FACING,AGEPOSSESSION,NEARBYLOCATIONS,DESCRIPTION,FURNISHDETAILS,FEATURES,RATING
1067,3 Bedroom House for sale in Sector 23A Gurgaon,nan,1.20,6230.0,(179 sq.m.) Plot Area,Plot area 214(178.93 sq.m.)Built Up area: 1500...,3,2,2,not available,"Sector 23, Sector 23A Gurgaon, Gurgaon, Haryana",3,NaN,0 to 1 Year Old,"['HUDA Sector 23 Market', 'Palam triangle', 'P...",Property sale in huda sector 23a plot size 212...,"['5 Fan', '1 Exhaust Fan', '2 Geyser', '1 Micr...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Safety5 out of 5', ..."
945,5 Bedroom House for sale in Sector 39 Gurgaon,nan,15.00,33333.0,(418 sq.m.) Plot Area,Plot area 500(418.06 sq.m.),5,5,3+,servant room,"Sector 39 Gurgaon, Gurgaon, Haryana",4,NaN,5 to 10 Year Old,"['Rajiv Chowk Mosque', 'State bank of india AT...",Near opposite of madanta hospital sector -39 r...,"['5 Wardrobe', '5 Fan', '1 Exhaust Fan', '5 Ge...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment4 out of 5', 'Safety4 out of 5', ..."
251,8 Bedroom House for sale in Sector 56 Gurgaon,nan,7.25,29336.0,(253 sq.m.) Plot Area,Plot area 303(253.35 sq.m.),8,8,3+,not available,"Sector 56 Gurgaon, Gurgaon, Haryana",0,North-East,5 to 10 Year Old,"['Sector metro station', 'Sector metro station...","The property is located in sector 56, next to ...","['15 Fan', '15 Light', '1 Modular Kitchen', 'N...","['High Ceiling Height', 'Natural Light', 'Airy...","['Environment4 out of 5', 'Lifestyle5 out of 5..."

In [358]:
data1['FACING']

0       North-East
1              NaN
2             West
3            North
4             West
5             East
6             East
7              NaN
8       North-East
9             West
10            West
11           North
12           North
13           North
14            West
15            East
16      South-West
17      North-East
18           South
19           North
20            West
21      North-East
22             NaN
23            East
24            East
25      North-East
26      South-East
27      North-East
28      North-West
29             NaN
30            East
31           North
32            East
33      North-East
34             NaN
35      South-East
36      North-East
37           North
38            East
39           North
40           North
41            East
42      South-East
43      North-West
44            West
45      North-East
46            East
47            East
48           North
49           North
50           South
51      South-West
52      North-East
53      South-East
54            East
55           South
56           North
57             NaN
58            East
59            East
73      North-East
74           North
77             NaN
78      South-East
92             NaN
93            East
103     North-East
104     North-East
114     South-East
119     South-East
120     North-East
121          North
122          North
125           East
126          South
127     South-East
129           East
130           East
131           West
132     North-West
133     North-East
134           East
135     North-West
136     North-West
137     North-West
138     North-West
139     North-East
140          North
141           East
142           East
143     North-West
144           West
145           West
146     South-West
147     North-East
148          North
149           East
150           East
151     North-East
152          North
153           East
154           West
155     North-East
156           East
157          South
158          North
159           West
160     South-East
161     South-East
162          South
163     South-West
164          North
165     North-East
166     North-East
167          South
168           East
169           West
170     South-West
171           West
172     North-East
173     North-East
174           East
175     North-East
176     North-East
177           East
200          North
201           East
202     North-East
203            NaN
204           East
205            NaN
206            NaN
207     North-East
208     North-East
209          North
210     South-West
211     North-West
212            NaN
213            NaN
214     North-East
215     North-East
216     South-West
217           East
218            NaN
219            NaN
220     South-East
221            NaN
222           East
223            NaN
224            NaN
225          South
226            NaN
227     North-East
228          North
229            NaN
230            NaN
231            NaN
232           East
233            NaN
234            NaN
235            NaN
236            NaN
237            NaN
238            NaN
239            NaN
240            NaN
241            NaN
242            NaN
243     North-East
244            NaN
245            NaN
246           West
247          South
248     North-East
249          South
250           East
251     North-East
252            NaN
253            NaN
254            NaN
255           East
256           East
257     North-East
258     South-East
259           East
260           East
261            NaN
262            NaN
263          North
264     North-East
265            NaN
266          North
267            NaN
268            NaN
269            NaN
270            NaN
271            NaN
272            NaN
273            NaN
274            NaN
275            NaN
276            NaN
277           East
278     South-West
279            NaN
280            NaN
281            NaN
282           East
283            NaN
284          South
285           East
286           East
287          North
288           East
289            NaN
290            NaN
291            NaN
292            NaN
293            NaN
294            NaN
295            NaN
296            NaN
297            NaN
298            NaN
299            NaN
300            NaN
301           East
302            NaN
303            NaN
304            NaN
305          South
306            NaN
307     North-East
309     South-East
310           East
311          North
314            NaN
315     North-East
316           East
317          North
318            NaN
320          North
321            NaN
322            NaN
323            NaN
324     North-West
325          North
326            NaN
332            NaN
333          North
334            NaN
335            NaN
336            NaN
337            NaN
338     South-East
339            NaN
340            NaN
341            NaN
342            NaN
343            NaN
344            NaN
345            NaN
346            NaN
347            NaN
348     North-East
349            NaN
350            NaN
351            NaN
352            NaN
357            NaN
370            NaN
374            NaN
375            NaN
376     North-East
377            NaN
378            NaN
379            NaN
380          North
381            NaN
382     South-West
383     South-East
384          North
385            NaN
386            NaN
387           East
388            NaN
389     South-East
390     North-East
391            NaN
392            NaN
393            NaN
394           East
395           East
396     North-East
397            NaN
398            NaN
399           West
400     South-East
401            NaN
402            NaN
403            NaN
404           West
405            NaN
406            NaN
407     North-East
408            NaN
409            NaN
410          South
411            NaN
412           East
413          North
414           West
415            NaN
416            NaN
417            NaN
418            NaN
419            NaN
420          North
421            NaN
422            NaN
423     North-East
424            NaN
425            NaN
426            NaN
427            NaN
428           East
429           West
430            NaN
431            NaN
432          North
433            NaN
434            NaN
435            NaN
436           East
437     South-West
438           West
439            NaN
440            NaN
441     South-East
442            NaN
443            NaN
444          North
445     South-East
446            NaN
447            NaN
448     North-West
449     North-West
450            NaN
451          North
452     North-East
453            NaN
454            NaN
455           East
456     North-East
457            NaN
458            NaN
459            NaN
460            NaN
461           East
462            NaN
463     South-West
464          North
465           East
466     South-East
467           East
468           West
469            NaN
470            NaN
471            NaN
472           West
473            NaN
474           East
475     North-West
476            NaN
477          North
478          South
479     North-East
480            NaN
481            NaN
482     North-West
483            NaN
484     North-West
485     North-East
486            NaN
487     North-East
488     South-East
489     North-West
490            NaN
491          North
492     North-East
493            NaN
494            NaN
495     North-East
496           East
497          South
498     South-East
499            NaN
500            NaN
501            NaN
502           East
503     North-East
504           East
505            NaN
506            NaN
507     North-East
508          South
509          South
510            NaN
511           West
512          North
513          South
514          North
515            NaN
516            NaN
517            NaN
518            NaN
519            NaN
520     North-West
521            NaN
522            NaN
523            NaN
524            NaN
525            NaN
526            NaN
527            NaN
528           East
529          North
530            NaN
531     North-East
532            NaN
533           East
534            NaN
535           East
536            NaN
537           East
538            NaN
539            NaN
540          North
541            NaN
542            NaN
543          North
544            NaN
545            NaN
546            NaN
547           East
548            NaN
549            NaN
550          North
551     North-East
552          North
553           East
554            NaN
555     North-East
556            NaN
557            NaN
558            NaN
559     South-East
560            NaN
561           West
562            NaN
563           West
564          North
565     South-West
566     North-East
567            NaN
568     North-East
569            NaN
570            NaN
571     South-East
572          South
573            NaN
574           East
575     North-East
576          South
577          South
578            NaN
579            NaN
580            NaN
581           East
582           East
583            NaN
584            NaN
585            NaN
586            NaN
587          North
588            NaN
589            NaN
590          South
591            NaN
592            NaN
593     North-East
594            NaN
595            NaN
596     North-East
597            NaN
598           East
599           West
600          North
601           East
602            NaN
603            NaN
604            NaN
605     South-West
606            NaN
607            NaN
608            NaN
609            NaN
610          North
611            NaN
612          North
613            NaN
614            NaN
615            NaN
616            NaN
617            NaN
618            NaN
619            NaN
620            NaN
621            NaN
622     North-East
623     North-West
624            NaN
625            NaN
626           East
627           East
628     North-East
629            NaN
630            NaN
631     North-East
632            NaN
633            NaN
634           East
635     North-East
636            NaN
637          North
638            NaN
639           East
640            NaN
641            NaN
642            NaN
643            NaN
644            NaN
645            NaN
646          North
647            NaN
648            NaN
649     North-West
650            NaN
651     South-East
652           East
653            NaN
654            NaN
655     South-East
656            NaN
657           East
658     North-West
659           East
660     North-East
661           West
662           East
663           East
664     North-West
665            NaN
666            NaN
667     North-East
668            NaN
669     North-East
670            NaN
671            NaN
672           East
673            NaN
674           East
675     South-West
676           West
677            NaN
678            NaN
679          North
680           West
681     South-East
682     North-East
683          North
684            NaN
685           East
686           West
687            NaN
688          North
689          North
690            NaN
691            NaN
692           East
693           East
694           East
695     North-East
696          North
697           East
698          North
699           West
700     North-East
701            NaN
702     North-East
703            NaN
704     North-West
705           East
706           West
707           West
708     North-East
709           East
710           East
711            NaN
712          South
713            NaN
714            NaN
715           East
716           East
717     South-East
718           West
719     North-West
720            NaN
721          South
722     North-East
723     North-West
724            NaN
725     North-East
726           East
727           East
728           East
729     North-East
730           East
731           East
732     North-West
733           East
734            NaN
735     North-East
736            NaN
737     North-West
738           East
739           East
740          North
741     North-East
742          North
743          North
744           East
745          North
746     North-East
747     North-East
748           West
749     North-East
750     North-East
751     North-East
752            NaN
753            NaN
754           East
755          South
756           East
757     North-West
758     North-West
759           West
760     North-East
761            NaN
762          North
763            NaN
764          North
765     North-West
766            NaN
767           East
768     South-West
769           East
770     North-East
771           East
772            NaN
773          North
774            NaN
775     North-East
776     North-East
777           East
778     North-East
779     North-East
780           East
781           East
782           East
783     South-East
784            NaN
785           East
786           West
787           West
788     North-East
789     North-West
790          South
791     South-East
792          North
793           East
794           West
795           East
796          North
797           East
798           West
799           East
800     North-East
801     North-East
802           East
803     North-East
804     North-East
805     South-West
806           East
807           West
808          North
809     North-East
810           East
811     North-East
812          North
813           East
814     North-East
815            NaN
816     North-East
817     North-East
818           West
819          North
820          North
821          North
822          South
823     South-West
824     North-East
825     South-East
826           East
827          South
828          North
829            NaN
830           East
831           East
832           West
833     North-East
834          South
835           East
836     North-West
837           East
838     North-East
839          North
840            NaN
841            NaN
842     South-East
843           West
844     North-East
845           East
846          North
847           East
848           East
849           East
850     North-West
851     North-East
852     North-East
853            NaN
854          North
855            NaN
856           East
857            NaN
858          North
859     North-East
860          North
861           East
862     North-East
863           East
864            NaN
865            NaN
866            NaN
867            NaN
868     North-East
869     North-West
870     South-West
871          North
872           West
873           West
874           East
875     North-East
876     North-East
877           West
878           East
879     North-East
880     North-East
881            NaN
882          North
883          North
884     North-West
885     North-East
886           East
887     North-West
888          North
889           East
890     North-East
891     South-East
892           West
893     North-East
895           West
896           East
897     North-East
898     North-West
899            NaN
900     North-West
901            NaN
902          North
903     South-West
904            NaN
905     North-East
906     North-West
907           East
908           East
909          North
910          North
911     South-East
912          South
913           West
914          South
915     North-East
916          North
917           East
918           East
919           East
920     North-East
921           East
922     North-East
923     North-East
924     South-West
925     North-East
926           West
927           East
928          North
929     North-East
930           West
931           West
932     North-East
933           East
934     South-West
935          South
936     North-East
937            NaN
938          North
939            NaN
940           East
941           East
942     North-East
943     North-East
944           West
945            NaN
946     North-East
947     North-East
948          North
949           East
950     North-East
951           East
952            NaN
953     North-East
954           West
955           West
956     North-West
957           West
958     North-East
959          North
960           East
961           East
962     North-East
963           West
964           East
965     North-East
966     North-East
967           West
968           East
969            NaN
970           East
971          South
972     North-East
973     North-East
974     North-East
975     North-East
976     North-East
977          North
978          South
979     South-West
980          North
981     North-East
982          North
983           East
984           East
985           East
986          North
987           East
988           East
989           East
990          North
991          North
992          North
993          North
994          North
995     South-East
996           East
997          North
998     North-East
999     North-East
1000    North-West
1001          East
1002    North-East
1003    South-West
1004          West
1005          East
1006           NaN
1007         South
1008          West
1009          West
1010           NaN
1011           NaN
1012         North
1013          West
1014    South-East
1015          West
1016          West
1017          East
1018         North
1019    North-East
1020         North
1021          West
1022           NaN
1023          West
1024         North
1025    North-East
1026          East
1027         North
1028          East
1029          West
1030         North
1031          West
1032          East
1033          East
1034    North-East
1035           NaN
1036         North
1037    North-East
1038    North-East
1039          East
1040          East
1041    North-East
1042    South-East
1043    North-East
1044          West
1045    North-East
1046    North-East
1047         North
1048    North-East
1049          West
1050          West
1051          East
1052           NaN
1053          East
1054          East
1055          East
1056          East
1057    North-West
1058          East
1059         North
1060    South-East
1061         South
1062           NaN
1063          East
1064           NaN
1065          West
1066    North-East
1067           NaN
1068          West
1069          East
1070         North
1071           NaN
1072          East
1073          East
1074          East
1075    North-East
1076    North-East
1077    South-East
1078    North-West
1079    South-West
1080    South-West
1081    North-West
1082    South-East
1083    North-East
1084    North-West
1085           NaN
1086    North-East
1087         North
1088          East
1089          West
1090           NaN
Name: FACING, dtype: object

In [359]:
data1['FACING'].isnull().sum()

313

In [360]:
data1['FACING'].value_counts()

FACING
East          181
North-East    159
North         114
West           75
North-West     44
South-East     40
South          36
South-West     25
Name: count, dtype: int64

In [361]:
data1['FACING'].fillna('na',inplace=True)

In [362]:
data1['FACING'].value_counts()

FACING
na            313
East          181
North-East    159
North         114
West           75
North-West     44
South-East     40
South          36
South-West     25
Name: count, dtype: int64

In [363]:
data1['FACING'] = data1['FACING'].str.lower()

In [364]:
data1.columns

Index(['PROPERTY_NAME', 'SOCIETY', 'PRICE', 'PRICE_PER_SQFT', 'AREA',
       'AREAWITHTYPE', 'BEDROOM', 'BATHROOM', 'BALCONY', 'ADDITIONALROOM',
       'ADDRESS', 'FLOORNUM', 'FACING', 'AGEPOSSESSION', 'NEARBYLOCATIONS',
       'DESCRIPTION', 'FURNISHDETAILS', 'FEATURES', 'RATING'],
      dtype='object')

In [365]:
data1.insert(loc=4,column='AREA2',value=round((data1['PRICE']*10000000)/data1['PRICE_PER_SQFT']))

In [366]:
data1.sample(4)

,PROPERTY_NAME,SOCIETY,PRICE,PRICE_PER_SQFT,AREA2,AREA,AREAWITHTYPE,BEDROOM,BATHROOM,BALCONY,ADDITIONALROOM,ADDRESS,FLOORNUM,FACING,AGEPOSSESSION,NEARBYLOCATIONS,DESCRIPTION,FURNISHDETAILS,FEATURES,RATING
649,8 Bedroom House for sale in C Block Sushant Lo...,ansal,1.85,308333.0,60.0,(6 sq.m.) Plot Area,Plot area 60(5.57 sq.m.),8,8,3+,not available,"C Block Sushant Lok Phase 1, Gurgaon, Haryana",5,north-west,1 to 5 Year Old,"['Huda city centre metro station', 'Sector 42-...","Corner property, every room has windows, prope...","['1 Water Purifier', '1 Fridge', '1 Stove', 'N...","['Private Garden / Terrace', 'Water purifier',...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
444,3 Bedroom House for sale in Manesar,nan,2.00,14954.0,1337.0,(124 sq.m.) Plot Area,Plot area 1337.4(124.25 sq.m.),3,1,0,not available,"Manesar, Gurgaon, Haryana",3,north,5 to 10 Year Old,"['Dr. Sahil Clinic', 'Pooja Clinic', 'Yadav De...",Well maintained spacious rooms with well clean...,[],"['Private Garden / Terrace', 'Water Storage']","['Environment4 out of 5', 'Lifestyle3.5 out of..."
1018,4 Bedroom House for sale in Sector 15 Part 2,nan,1.45,12393.0,1170.0,(109 sq.m.) Plot Area,Plot area 130(108.7 sq.m.)Built Up area: 130 s...,4,4,2,others,"Patel Nagar 525, Sector 15 Part 2, Gurgaon, Ha...",2,north,10+ Year Old,"['Hanuman Mandir', 'State bank of india ATM', ...",House for sale 130 sqyard old house patel naga...,NaN,"['Maintenance Staff', 'Water Storage']","['Environment5 out of 5', 'Safety5 out of 5', ..."
462,3 Bedroom House for sale in Ashok Vihar Phase 2,nan,1.00,11111.0,900.0,(84 sq.m.) Plot Area,Plot area 900(83.61 sq.m.),3,4,2,not available,"Ashok Vihar Phase 2, Gurgaon, Haryana",2,na,1 to 5 Year Old,"['Sheetla Mata Mandir', 'Chintapurni Mandir', ...",I have a house/villa available for sale in ash...,[],NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."

In [367]:
data1.drop(columns='AREA',inplace=True)

In [368]:
data1.sample(2)

,PROPERTY_NAME,SOCIETY,PRICE,PRICE_PER_SQFT,AREA2,AREAWITHTYPE,BEDROOM,BATHROOM,BALCONY,ADDITIONALROOM,ADDRESS,FLOORNUM,FACING,AGEPOSSESSION,NEARBYLOCATIONS,DESCRIPTION,FURNISHDETAILS,FEATURES,RATING
721,5 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,9.50,26389.0,3600.0,Plot area 400(334.45 sq.m.),5,5,3+,"pooja room,study room,store room,servant room","Sector 109 Gurgaon, Gurgaon, Haryana",2,south,1 to 5 Year Old,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",400sq yard independent villa - 5 bhk\nSobha in...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
704,6 Bedroom House for sale in Sector 51 Gurgaon,nan,2.25,25000.0,900.0,Plot area 100(83.61 sq.m.),6,3,3+,not available,"Sector 51 Gurgaon, Gurgaon, Haryana",3,north-west,1 to 5 Year Old,"['Radhakrishna Shani Mandir', 'Standard charte...",100 sqyd built up house with stilt and 3 floor...,"['2 Wardrobe', '7 Fan', '1 Exhaust Fan', '7 Li...","['High Ceiling Height', 'False Ceiling Lightin...","['Environment5 out of 5', 'Lifestyle4 out of 5..."

In [369]:
data1.rename(columns={'AREA2':'AREA'},inplace=True)

In [370]:
data1.head()

,PROPERTY_NAME,SOCIETY,PRICE,PRICE_PER_SQFT,AREA,AREAWITHTYPE,BEDROOM,BATHROOM,BALCONY,ADDITIONALROOM,ADDRESS,FLOORNUM,FACING,AGEPOSSESSION,NEARBYLOCATIONS,DESCRIPTION,FURNISHDETAILS,FEATURES,RATING
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,2610.0,Plot area 290(242.48 sq.m.),5,4,3+,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3,north-east,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,nan,5.70,105751.0,539.0,Plot area 539(50.07 sq.m.),5,4,2,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2,na,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,nan,2.10,38251.0,549.0,Plot area 61(51 sq.m.),10,10,3+,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5,west,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,nan,5.00,43066.0,1161.0,Plot area 129(107.86 sq.m.),21,21,3+,servant room,"Sector 54 Gurgaon, Gurgaon, Haryana",5,north,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,nan,3.00,53763.0,558.0,Plot area 62(51.84 sq.m.),12,12,3+,others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5,west,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [371]:
data1.insert(loc=1,column='PROPERTY_TYPE',value='houses')

In [372]:
data1.head()

,PROPERTY_NAME,PROPERTY_TYPE,SOCIETY,PRICE,PRICE_PER_SQFT,AREA,AREAWITHTYPE,BEDROOM,BATHROOM,BALCONY,ADDITIONALROOM,ADDRESS,FLOORNUM,FACING,AGEPOSSESSION,NEARBYLOCATIONS,DESCRIPTION,FURNISHDETAILS,FEATURES,RATING
0,5 Bedroom House for sale in Sector 70A Gurgaon,houses,bptp visionnaire,5.25,20115.0,2610.0,Plot area 290(242.48 sq.m.),5,4,3+,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3,north-east,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,houses,nan,5.70,105751.0,539.0,Plot area 539(50.07 sq.m.),5,4,2,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2,na,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,houses,nan,2.10,38251.0,549.0,Plot area 61(51 sq.m.),10,10,3+,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5,west,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,houses,nan,5.00,43066.0,1161.0,Plot area 129(107.86 sq.m.),21,21,3+,servant room,"Sector 54 Gurgaon, Gurgaon, Haryana",5,north,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,houses,nan,3.00,53763.0,558.0,Plot area 62(51.84 sq.m.),12,12,3+,others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5,west,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."